export const messages = {
  'pt-PT': {
    'nav.overview': 'Visão geral', 'nav.attendance': 'Ponto', 'nav.selfService': 'Meu RH', 'nav.request': 'Solicitar', 'nav.approvals': 'Aprovações', 'nav.people360': 'People 360', 'nav.more': 'Mais',
    'operations.title': 'Centro de operações', 'operations.security': 'Segurança', 'operations.privacy': 'Privacidade', 'operations.setup': 'Setup', 'operations.rules': 'Regras', 'operations.performance': 'Performance', 'operations.exceptions': 'Exceções', 'operations.analytics': 'Analytics', 'operations.integrations': 'Integrações', 'operations.roles': 'Papéis', 'operations.import': 'Importar', 'operations.offboarding': 'Offboarding', 'operations.access': 'Acessos', 'operations.payroll': 'Folha', 'operations.audit': 'Auditoria', 'operations.billing': 'Faturamento',
    'operations.global': 'Idioma e região', 'global.title': 'Localização global', 'global.subtitle': 'Idioma, país, moeda e fuso horário da empresa', 'global.country': 'País', 'global.language': 'Idioma', 'global.currency': 'Moeda', 'global.timezone': 'Fuso horário', 'global.weekStart': 'Início da semana', 'global.save': 'Guardar alterações', 'global.saving': 'A guardar…', 'global.saved': 'Configuração guardada', 'global.cancel': 'Cancelar', 'global.firstDay': 'Primeiro dia', 'global.languageHint': 'Pode ser diferente da região para empresas multinacionais', 'global.currencyHint': 'Formato monetário apresentado no produto',
    'state.stable': 'Operação estável', 'state.attention': 'Atenção necessária', 'state.updated': 'Atualizado às', 'state.syncing': 'A sincronizar dados reais', 'common.active': 'Ativo', 'common.configured': 'Configurado', 'common.pending': 'Pendente', 'common.none': 'Nenhum',
  },
  'en-US': {
    'nav.overview': 'Overview', 'nav.attendance': 'Time tracking', 'nav.selfService': 'My HR', 'nav.request': 'Request', 'nav.approvals': 'Approvals', 'nav.people360': 'People 360', 'nav.more': 'More',
    'operations.title': 'Operations center', 'operations.security': 'Security', 'operations.privacy': 'Privacy', 'operations.setup': 'Setup', 'operations.rules': 'Rules', 'operations.performance': 'Performance', 'operations.exceptions': 'Exceptions', 'operations.analytics': 'Analytics', 'operations.integrations': 'Integrations', 'operations.roles': 'Roles', 'operations.import': 'Import', 'operations.offboarding': 'Offboarding', 'operations.access': 'Access', 'operations.payroll': 'Payroll', 'operations.audit': 'Audit', 'operations.billing': 'Billing',
    'operations.global': 'Language & region', 'global.title': 'Global localization', 'global.subtitle': 'Company language, country, currency and timezone', 'global.country': 'Country', 'global.language': 'Language', 'global.currency': 'Currency', 'global.timezone': 'Timezone', 'global.weekStart': 'Week starts on', 'global.save': 'Save changes', 'global.saving': 'Saving…', 'global.saved': 'Configuration saved', 'global.cancel': 'Cancel', 'global.firstDay': 'First day', 'global.languageHint': 'Can differ from the region for multinational companies', 'global.currencyHint': 'Monetary format shown across the product',
    'state.stable': 'Operations stable', 'state.attention': 'Attention required', 'state.updated': 'Updated at', 'state.syncing': 'Syncing live data', 'common.active': 'Active', 'common.configured': 'Configured', 'common.pending': 'Pending', 'common.none': 'None',
  },
  'es-ES': {
    'nav.overview': 'Vista general', 'nav.attendance': 'Control horario', 'nav.selfService': 'Mi RR. HH.', 'nav.request': 'Solicitar', 'nav.approvals': 'Aprobaciones', 'nav.people360': 'People 360', 'nav.more': 'Más',
    'operations.title': 'Centro de operaciones', 'operations.security': 'Seguridad', 'operations.privacy': 'Privacidad', 'operations.setup': 'Configuración', 'operations.rules': 'Reglas', 'operations.performance': 'Rendimiento', 'operations.exceptions': 'Excepciones', 'operations.analytics': 'Analítica', 'operations.integrations': 'Integraciones', 'operations.roles': 'Roles', 'operations.import': 'Importar', 'operations.offboarding': 'Salida', 'operations.access': 'Accesos', 'operations.payroll': 'Nómina', 'operations.audit': 'Auditoría', 'operations.billing': 'Facturación',
    'operations.global': 'Idioma y región', 'global.title': 'Localización global', 'global.subtitle': 'Idioma, país, moneda y zona horaria de la empresa', 'global.country': 'País', 'global.language': 'Idioma', 'global.currency': 'Moneda', 'global.timezone': 'Zona horaria', 'global.weekStart': 'Inicio de semana', 'global.save': 'Guardar cambios', 'global.saving': 'Guardando…', 'global.saved': 'Configuración guardada', 'global.cancel': 'Cancelar', 'global.firstDay': 'Primer día', 'global.languageHint': 'Puede ser diferente de la región en empresas multinacionales', 'global.currencyHint': 'Formato monetario mostrado en el producto',
    'state.stable': 'Operación estable', 'state.attention': 'Se requiere atención', 'state.updated': 'Actualizado a las', 'state.syncing': 'Sincronizando datos reales', 'common.active': 'Activo', 'common.configured': 'Configurado', 'common.pending': 'Pendiente', 'common.none': 'Ninguno',
  },
  'fr-FR': {
    'nav.overview': 'Vue d’ensemble', 'nav.attendance': 'Temps de travail', 'nav.selfService': 'Mon RH', 'nav.request': 'Demander', 'nav.approvals': 'Approbations', 'nav.people360': 'People 360', 'nav.more': 'Plus',
    'operations.title': 'Centre des opérations', 'operations.security': 'Sécurité', 'operations.privacy': 'Confidentialité', 'operations.setup': 'Configuration', 'operations.rules': 'Règles', 'operations.performance': 'Performance', 'operations.exceptions': 'Exceptions', 'operations.analytics': 'Analytique', 'operations.integrations': 'Intégrations', 'operations.roles': 'Rôles', 'operations.import': 'Importer', 'operations.offboarding': 'Départ', 'operations.access': 'Accès', 'operations.payroll': 'Paie', 'operations.audit': 'Audit', 'operations.billing': 'Facturation',
    'operations.global': 'Langue et région', 'global.title': 'Localisation globale', 'global.subtitle': 'Langue, pays, devise et fuseau horaire de l’entreprise', 'global.country': 'Pays', 'global.language': 'Langue', 'global.currency': 'Devise', 'global.timezone': 'Fuseau horaire', 'global.weekStart': 'Début de semaine', 'global.save': 'Enregistrer', 'global.saving': 'Enregistrement…', 'global.saved': 'Configuration enregistrée', 'global.cancel': 'Annuler', 'global.firstDay': 'Premier jour', 'global.languageHint': 'Peut différer de la région pour les entreprises multinationales', 'global.currencyHint': 'Format monétaire affiché dans le produit',
    'state.stable': 'Opérations stables', 'state.attention': 'Attention requise', 'state.updated': 'Mis à jour à', 'state.syncing': 'Synchronisation des données', 'common.active': 'Actif', 'common.configured': 'Configuré', 'common.pending': 'En attente', 'common.none': 'Aucun',
  },
  'de-DE': {
    'nav.overview': 'Übersicht', 'nav.attendance': 'Zeiterfassung', 'nav.selfService': 'Meine HR', 'nav.request': 'Anfrage', 'nav.approvals': 'Freigaben', 'nav.people360': 'People 360', 'nav.more': 'Mehr',
    'operations.title': 'Operationszentrum', 'operations.security': 'Sicherheit', 'operations.privacy': 'Datenschutz', 'operations.setup': 'Einrichtung', 'operations.rules': 'Regeln', 'operations.performance': 'Leistung', 'operations.exceptions': 'Ausnahmen', 'operations.analytics': 'Analysen', 'operations.integrations': 'Integrationen', 'operations.roles': 'Rollen', 'operations.import': 'Import', 'operations.offboarding': 'Offboarding', 'operations.access': 'Zugriffe', 'operations.payroll': 'Lohnabrechnung', 'operations.audit': 'Audit', 'operations.billing': 'Abrechnung',
    'operations.global': 'Sprache & Region', 'global.title': 'Globale Lokalisierung', 'global.subtitle': 'Unternehmenssprache, Land, Währung und Zeitzone', 'global.country': 'Land', 'global.language': 'Sprache', 'global.currency': 'Währung', 'global.timezone': 'Zeitzone', 'global.weekStart': 'Wochenbeginn', 'global.save': 'Änderungen speichern', 'global.saving': 'Speichern…', 'global.saved': 'Konfiguration gespeichert', 'global.cancel': 'Abbrechen', 'global.firstDay': 'Erster Tag', 'global.languageHint': 'Kann bei multinationalen Unternehmen von der Region abweichen', 'global.currencyHint': 'Währungsformat im Produkt',
    'state.stable': 'Betrieb stabil', 'state.attention': 'Aufmerksamkeit erforderlich', 'state.updated': 'Aktualisiert um', 'state.syncing': 'Live-Daten werden synchronisiert', 'common.active': 'Aktiv', 'common.configured': 'Konfiguriert', 'common.pending': 'Ausstehend', 'common.none': 'Keine',
  },
};

export function translate(locale, key, fallback = key) {
  const selected = messages[locale] || messages['en-US'];
  return selected[key] || messages['en-US'][key] || messages['pt-PT'][key] || fallback;
}
