import { useMemo, useRef, useState } from 'react';
import { CheckCircle2, Download, FileUp, Loader2, UsersRound, X } from 'lucide-react';
import { createClient } from '@supabase/supabase-js';

const supabase = createClient(import.meta.env.VITE_SUPABASE_URL, import.meta.env.VITE_SUPABASE_PUBLISHABLE_KEY, { auth: { persistSession: true, autoRefreshToken: true } });
const TEMPLATE='employee_code;full_name;email;phone;nif;hire_date\n001;Maria Silva;maria@empresa.pt;+351910000000;123456789;2026-09-17\n';

function parseCsv(text){const lines=text.replace(/^\ufeff/,'').split(/\r?\n/).filter(Boolean);if(!lines.length)return [];const split=(line)=>line.includes(';')?line.split(';'):line.split(',');const headers=split(lines[0]).map((h)=>h.trim().toLowerCase());return lines.slice(1).map((line)=>{const values=split(line);return Object.fromEntries(headers.map((h,i)=>[h,(values[i]||'').trim()]));});}

export default function EmployeeImportPanel({ profile, onClose }){
 const input=useRef(null); const [rows,setRows]=useState([]); const [fileName,setFileName]=useState(''); const [busy,setBusy]=useState(false); const [result,setResult]=useState(null); const [error,setError]=useState('');
 const valid=useMemo(()=>rows.filter((row)=>row.full_name && row.employee_code),[rows]); const invalid=rows.length-valid.length;
 const read=(file)=>{setError('');setResult(null);setFileName(file?.name||'');if(!file)return;const reader=new FileReader();reader.onload=()=>{try{const parsed=parseCsv(String(reader.result||''));if(!parsed.length)throw new Error('O CSV não contém linhas de dados.');if(parsed.length>500)throw new Error('Limite máximo por importação: 500 colaboradores.');setRows(parsed);}catch(e){setRows([]);setError(e.message);}};reader.readAsText(file,'utf-8');};
 const importRows=async()=>{setBusy(true);setError('');setResult(null);let created=0;const failures=[];for(const row of valid){const {error:rpcError}=await supabase.rpc('create_employee',{p_employee_code:row.employee_code,p_full_name:row.full_name,p_email:row.email||null,p_phone:row.phone||null,p_nif:row.nif||null,p_department_id:row.department_id||null,p_position_id:row.position_id||null,p_hire_date:row.hire_date||null});if(rpcError)failures.push(`${row.employee_code} · ${row.full_name}: ${rpcError.message}`);else created+=1;}setResult({created,failed:failures.length,failures});setBusy(false);};
 const downloadTemplate=()=>{const blob=new Blob([`\ufeff${TEMPLATE}`],{type:'text/csv;charset=utf-8'});const url=URL.createObjectURL(blob);const a=document.createElement('a');a.href=url;a.download='te-connect-colaboradores-modelo.csv';a.click();URL.revokeObjectURL(url);};
 return <div style={{position:'fixed',inset:0,zIndex:198,overflow:'auto',background:'#07101f',color:'#fff',padding:24}}><div style={{maxWidth:900,margin:'0 auto'}}><header style={{display:'flex',justifyContent:'space-between',alignItems:'flex-end',gap:12,marginBottom:16}}><div><div style={{color:'#73a7ff',fontSize:10,fontWeight:800,textTransform:'uppercase',letterSpacing:'.12em'}}>People Operations</div><h1 style={{margin:'5px 0',fontSize:28}}>Importar colaboradores</h1><p style={{margin:0,color:'rgba(255,255,255,.5)',fontSize:11}}>Carregue até 500 colaboradores por ficheiro CSV.</p></div><div style={{display:'flex',gap:7}}><button onClick={downloadTemplate} style={{border:'1px solid rgba(255,255,255,.1)',background:'rgba(255,255,255,.045)',color:'#fff',borderRadius:9,padding:'9px 11px',display:'inline-flex',gap:7,alignItems:'center',fontSize:9}}><Download size={14}/> Modelo CSV</button><button onClick={onClose} style={{border:'1px solid rgba(255,255,255,.1)',background:'rgba(255,255,255,.045)',color:'#fff',borderRadius:9,padding:'9px 11px',display:'inline-flex',gap:7,alignItems:'center',fontSize:9}}><X size={14}/> Fechar</button></div></header>
 <section style={{border:'1px solid rgba(255,255,255,.09)',borderRadius:15,padding:18,background:'rgba(255,255,255,.035)',marginBottom:12}}><div style={{display:'flex',justifyContent:'space-between',gap:12,alignItems:'center'}}><div><div style={{display:'flex',alignItems:'center',gap:8}}><FileUp size={17}/><strong style={{fontSize:13}}>Ficheiro</strong></div><p style={{margin:'5px 0 0',color:'rgba(255,255,255,.45)',fontSize:9}}>Colunas obrigatórias: employee_code e full_name. Email, telefone, NIF e data de admissão são opcionais.</p></div><button onClick={()=>input.current?.click()} style={{border:'1px solid #3d7fff',background:'rgba(58,126,255,.14)',color:'#b4cbff',borderRadius:9,padding:'9px 12px',fontSize:9}}>Escolher CSV</button></div><input ref={input} type="file" accept=".csv,text/csv" onChange={(e)=>read(e.target.files?.[0])} style={{display:'none'}}/>{fileName&&<div style={{marginTop:13,padding:11,borderRadius:10,background:'rgba(255,255,255,.03)',fontSize:9}}>{fileName} · {rows.length} linhas · <strong>{valid.length} válidas</strong> · <strong>{invalid} inválidas</strong></div>}</section>
 {error&&<div style={{marginBottom:12,padding:11,borderRadius:10,background:'rgba(239,100,120,.08)',border:'1px solid rgba(239,100,120,.24)',color:'#ff9dab',fontSize:9}}>{error}</div>}
 {rows.length>0&&<><section style={{border:'1px solid rgba(255,255,255,.09)',borderRadius:15,padding:15,background:'rgba(255,255,255,.03)',marginBottom:12,overflow:'auto'}}><table style={{width:'100%',borderCollapse:'collapse',minWidth:700}}><thead><tr>{['Código','Nome','Email','Telefone','NIF','Admissão'].map((h)=><th key={h} style={{padding:'8px',borderBottom:'1px solid rgba(255,255,255,.08)',textAlign:'left',fontSize:8,color:'rgba(255,255,255,.4)'}}>{h}</th>)}</tr></thead><tbody>{rows.slice(0,30).map((row,i)=><tr key={i}><td style={{padding:8,fontSize:9}}>{row.employee_code||'—'}</td><td style={{padding:8,fontSize:9}}>{row.full_name||'—'}</td><td style={{padding:8,fontSize:9}}>{row.email||'—'}</td><td style={{padding:8,fontSize:9}}>{row.phone||'—'}</td><td style={{padding:8,fontSize:9}}>{row.nif||'—'}</td><td style={{padding:8,fontSize:9}}>{row.hire_date||'—'}</td></tr>)}</tbody></table>{rows.length>30&&<div style={{paddingTop:10,color:'rgba(255,255,255,.4)',fontSize:8}}>Pré-visualização limitada às primeiras 30 linhas.</div>}</section><div style={{display:'flex',justifyContent:'flex-end'}}><button disabled={busy||valid.length===0} onClick={importRows} style={{border:'1px solid #3f82ff',background:'linear-gradient(135deg,#3f82ff,#2459dd)',color:'#fff',borderRadius:9,padding:'10px 14px',display:'inline-flex',gap:7,alignItems:'center',fontSize:9}}>{busy?<Loader2 size={14} className="tc-spin"/>:<UsersRound size={14}/>} {busy?'A importar…':`Importar ${valid.length} colaboradores`}</button></div></>}
 {result&&<section style={{marginTop:12,padding:16,borderRadius:12,border:'1px solid rgba(39,201,132,.18)',background:'rgba(39,201,132,.06)'}}><div style={{display:'flex',alignItems:'center',gap:8}}><CheckCircle2 size={17} color="#57dca2"/><strong style={{fontSize:12}}>Importação concluída</strong></div><div style={{marginTop:8,fontSize:9,color:'rgba(255,255,255,.55)'}}>{result.created} criados · {result.failed} falharam.</div>{result.failures?.length>0&&<div style={{marginTop:10,maxHeight:160,overflow:'auto',fontSize:8,color:'#ff9dab'}}>{result.failures.map((item)=><div key={item} style={{padding:'4px 0'}}>{item}</div>)}</div>}</section>}
 <div style={{marginTop:13,padding:11,borderRadius:10,background:'rgba(255,255,255,.025)',color:'rgba(255,255,255,.4)',fontSize:8}}>A importação usa a mesma RPC protegida de criação de colaboradores, respeitando o tenant e os limites de subscrição.</div>
 </div></div>;
}
