import { useCallback, useEffect, useState } from 'react';
import { CalendarCheck, CheckCircle2, Clock3, FileWarning, RefreshCw, Send, X } from 'lucide-react';
import { createClient } from '@supabase/supabase-js';

const supabase=createClient(import.meta.env.VITE_SUPABASE_URL,import.meta.env.VITE_SUPABASE_PUBLISHABLE_KEY,{auth:{persistSession:true,autoRefreshToken:true}});
const today=()=>new Date().toISOString().slice(0,10);
const inputStyle={width:'100%',boxSizing:'border-box',padding:'10px',borderRadius:9,border:'1px solid rgba(255,255,255,.12)',background:'rgba(255,255,255,.045)',color:'#fff',fontSize:10};
function Button({children,icon:Icon,onClick,primary=false,disabled=false}){return <button type="button" onClick={onClick} disabled={disabled} style={{display:'inline-flex',alignItems:'center',justifyContent:'center',gap:7,padding:'9px 12px',borderRadius:9,border:primary?'1px solid #3e82ff':'1px solid rgba(255,255,255,.1)',background:primary?'linear-gradient(135deg,#3f82ff,#2459dd)':'rgba(255,255,255,.045)',color:'#fff',fontSize:9,opacity:disabled?.55:1}}>{Icon&&<Icon size={14}/>} {children}</button>}
function Field({label,children}){return <label style={{display:'grid',gap:5,color:'rgba(255,255,255,.55)',fontSize:9}}>{label}{children}</label>}
export default function EmployeeRequestCenter({profile,onClose}){
 const [types,setTypes]=useState([]); const [type,setType]=useState('vacation'); const [form,setForm]=useState({start_date:today(),end_date:today(),days:1,minutes:60,reason:'',absence_type_id:''}); const [message,setMessage]=useState(''); const [saving,setSaving]=useState(false); const [recent,setRecent]=useState([]);
 const load=useCallback(async()=>{if(!profile?.company_id)return;const [typesResult,vacResult,absResult,otResult]=await Promise.all([supabase.from('absence_types').select('id,name,requires_document,paid').eq('company_id',profile.company_id).eq('active',true).order('name'),supabase.from('vacation_requests').select('id,start_date,end_date,days,status,created_at').eq('company_id',profile.company_id).eq('employee_id',(await supabase.from('employees').select('id').eq('company_id',profile.company_id).eq('user_id',profile.user_id).maybeSingle()).data?.id||'').order('created_at',{ascending:false}).limit(6),supabase.from('absences').select('id,start_date,end_date,reason,status,created_at').eq('company_id',profile.company_id).order('created_at',{ascending:false}).limit(6),supabase.from('overtime_records').select('id,minutes,reason,status,created_at').eq('company_id',profile.company_id).order('created_at',{ascending:false}).limit(6)]);setTypes(typesResult.data||[]);setRecent([{kind:'Férias',rows:vacResult.data||[],map:(r)=>`${r.start_date} → ${r.end_date} · ${r.days} dias`},{kind:'Ausência',rows:absResult.data||[],map:(r)=>`${r.start_date} → ${r.end_date}${r.reason?` · ${r.reason}`:''}`},{kind:'Horas extra',rows:otResult.data||[],map:(r)=>`${r.minutes} min${r.reason?` · ${r.reason}`:''}`}]);},[profile?.company_id,profile?.user_id]);
 useEffect(()=>{load()},[load]);
 const save=async()=>{setSaving(true);setMessage('');try{if(type==='vacation'){const {data,error}=await supabase.rpc('create_my_vacation_request',{p_start_date:form.start_date,p_end_date:form.end_date,p_days:Number(form.days),p_reason:form.reason||null});if(error)throw error;if(!data)throw new Error('Pedido não criado.')}else if(type==='absence'){const {data,error}=await supabase.rpc('create_my_absence_request',{p_start_date:form.start_date,p_end_date:form.end_date,p_reason:form.reason||null,p_absence_type_id:form.absence_type_id||null});if(error)throw error;if(!data)throw new Error('Pedido não criado.')}else{const employee=await supabase.from('employees').select('id').eq('company_id',profile.company_id).eq('user_id',profile.user_id).maybeSingle();if(employee.error)throw employee.error;if(!employee.data?.id)throw new Error('Conta sem colaborador associado.');const {data,error}=await supabase.rpc('request_overtime',{p_minutes:Number(form.minutes),p_reason:form.reason||null,p_attendance_day_id:null});if(error)throw error;if(!data)throw new Error('Pedido não criado.')}setMessage('Pedido enviado para aprovação do RH/gestor.');setForm(f=>({...f,reason:'',days:1,minutes:60}));await load()}catch(error){setMessage(error.message||'Não foi possível enviar o pedido.')}finally{setSaving(false)}};
 return <div style={{position:'fixed',inset:0,zIndex:215,overflow:'auto',background:'#07101f',color:'#fff',padding:24}}><div style={{maxWidth:920,margin:'0 auto'}}><header style={{display:'flex',justifyContent:'space-between',alignItems:'flex-end',gap:12,marginBottom:16}}><div><div style={{color:'#71a6ff',fontSize:10,fontWeight:800,textTransform:'uppercase',letterSpacing:'.12em'}}>Employee Self Service</div><h1 style={{margin:'5px 0',fontSize:28}}>Solicitar no Meu RH</h1><p style={{margin:0,color:'rgba(255,255,255,.5)',fontSize:11}}>Envie pedidos diretamente para o fluxo de aprovação.</p></div><div style={{display:'flex',gap:7}}><Button icon={RefreshCw} onClick={load}>Atualizar</Button><Button icon={X} onClick={onClose}>Fechar</Button></div></header>
 {message&&<div style={{marginBottom:12,padding:11,borderRadius:10,border:'1px solid rgba(75,137,255,.22)',background:'rgba(58,121,255,.07)',color:'#b1c7ff',fontSize:9}}>{message}</div>}
 <div style={{display:'grid',gridTemplateColumns:'1fr 1fr 1fr',gap:9,marginBottom:12}}>{[['vacation','Férias',CalendarCheck],['absence','Ausência',FileWarning],['overtime','Horas extra',Clock3]].map(([id,label,Icon])=><button key={id} onClick={()=>setType(id)} style={{padding:14,borderRadius:12,border:type===id?'1px solid rgba(67,133,255,.52)':'1px solid rgba(255,255,255,.08)',background:type===id?'rgba(60,123,255,.12)':'rgba(255,255,255,.03)',color:'#fff',textAlign:'left'}}><Icon size={16}/><strong style={{display:'block',marginTop:7,fontSize:11}}>{label}</strong><small style={{display:'block',marginTop:3,color:'rgba(255,255,255,.42)',fontSize:8}}>Nova solicitação</small></button>)}</div>
 <section style={{border:'1px solid rgba(255,255,255,.09)',borderRadius:15,padding:17,background:'rgba(255,255,255,.035)',marginBottom:12}}>{type==='overtime'?<><div style={{display:'grid',gridTemplateColumns:'1fr 1fr',gap:10}}><Field label="Minutos"><input type="number" min="1" max="1440" value={form.minutes} onChange={e=>setForm(f=>({...f,minutes:e.target.value}))} style={inputStyle}/></Field><Field label="Motivo"><input value={form.reason} onChange={e=>setForm(f=>({...f,reason:e.target.value}))} style={inputStyle}/></Field></div></>:<><div style={{display:'grid',gridTemplateColumns:'1fr 1fr',gap:10}}><Field label="Início"><input type="date" value={form.start_date} onChange={e=>setForm(f=>({...f,start_date:e.target.value}))} style={inputStyle}/></Field><Field label="Fim"><input type="date" value={form.end_date} onChange={e=>setForm(f=>({...f,end_date:e.target.value}))} style={inputStyle}/></Field></div>{type==='vacation'?<Field label="Dias"><input type="number" min="0.5" step="0.5" value={form.days} onChange={e=>setForm(f=>({...f,days:e.target.value}))} style={inputStyle}/></Field>:<Field label="Tipo de ausência"><select value={form.absence_type_id} onChange={e=>setForm(f=>({...f,absence_type_id:e.target.value}))} style={inputStyle}><option value="">Selecionar</option>{types.map(t=><option key={t.id} value={t.id}>{t.name}{t.paid?' · paga':''}</option>)}</select></Field>}<div style={{marginTop:10}}><Field label="Motivo / observação"><textarea rows="4" value={form.reason} onChange={e=>setForm(f=>({...f,reason:e.target.value}))} style={inputStyle}/></Field></div></>}
 <div style={{display:'flex',justifyContent:'flex-end',marginTop:14}}><Button primary icon={Send} onClick={save} disabled={saving}>{saving?'A enviar…':'Enviar pedido'}</Button></div></section>
 <section style={{border:'1px solid rgba(255,255,255,.09)',borderRadius:15,padding:17,background:'rgba(255,255,255,.035)'}}><div style={{display:'flex',alignItems:'center',gap:8,marginBottom:12}}><CheckCircle2 size={16}/><strong style={{fontSize:13}}>Pedidos recentes</strong></div>{recent.flatMap(({kind,rows,map})=>rows.map((row)=><div key={`${kind}-${row.id}`} style={{display:'flex',justifyContent:'space-between',gap:10,padding:'8px 0',borderBottom:'1px solid rgba(255,255,255,.06)',fontSize:9}}><span><strong>{kind}</strong> · {map(row)}</span><span>{row.status}</span></div>))}</section>
 </div></div>;
}
