import { useCallback, useEffect, useState } from 'react';
import { Check, ClipboardCheck, LogOut, RefreshCw, ShieldCheck, UserRound, X } from 'lucide-react';
import { createClient } from '@supabase/supabase-js';

const supabase = createClient(import.meta.env.VITE_SUPABASE_URL, import.meta.env.VITE_SUPABASE_PUBLISHABLE_KEY, { auth: { persistSession: true, autoRefreshToken: true } });
const today=()=>new Date().toISOString().slice(0,10);
const ADMIN=new Set(['SUPER_ADMIN','COMPANY_ADMIN','RH']);

function Button({children,icon:Icon,onClick,primary=false,disabled=false}){return <button type="button" onClick={onClick} disabled={disabled} style={{display:'inline-flex',alignItems:'center',gap:7,padding:'9px 12px',borderRadius:9,border:primary?'1px solid #3e82ff':'1px solid rgba(255,255,255,.1)',background:primary?'linear-gradient(135deg,#3f82ff,#2358dd)':'rgba(255,255,255,.045)',color:'#fff',fontSize:9,opacity:disabled?.55:1}}>{Icon&&<Icon size={14}/>} {children}</button>}

export default function LifecycleCenter({profile,onClose}){
 const [employees,setEmployees]=useState([]); const [selected,setSelected]=useState(null); const [date,setDate]=useState(today()); const [reason,setReason]=useState(''); const [checks,setChecks]=useState({access:false,documents:false,devices:false,final:false}); const [loading,setLoading]=useState(true); const [busy,setBusy]=useState(false); const [message,setMessage]=useState('');
 const canManage=ADMIN.has(profile?.role);
 const load=useCallback(async()=>{if(!profile?.company_id)return;setLoading(true);const {data,error}=await supabase.from('employees').select('id,full_name,employee_code,email,status,termination_date,termination_reason,offboarding_checklist').eq('company_id',profile.company_id).order('full_name').limit(3000);if(error)setMessage(error.message);setEmployees(data||[]);if(!selected&&data?.[0])setSelected(data[0]);else if(selected){const refreshed=(data||[]).find((e)=>e.id===selected.id);if(refreshed)setSelected(refreshed);}setLoading(false);},[profile?.company_id,selected?.id]);
 useEffect(()=>{load();},[load]);
 const submit=async()=>{if(!selected)return;setBusy(true);setMessage('');const payload={access:checks.access,documents:checks.documents,devices:checks.devices,finalized:checks.final};const {data,error}=await supabase.rpc('offboard_employee_app',{p_employee_id:selected.id,p_termination_date:date,p_reason:reason||null,p_checklist:payload});if(error)setMessage(error.message);else{setMessage(data?.access_disabled?'Colaborador desligado e acesso de conta desativado.':'Colaborador desligado.');await load();}setBusy(false);};
 if(!canManage)return null;
 return <div style={{position:'fixed',inset:0,zIndex:186,overflow:'auto',background:'#07101f',color:'#fff',padding:24}}><div style={{maxWidth:1200,margin:'0 auto'}}>
  <header style={{display:'flex',justifyContent:'space-between',alignItems:'flex-end',gap:12,marginBottom:16}}><div><div style={{color:'#72a7ff',fontSize:10,fontWeight:800,textTransform:'uppercase',letterSpacing:'.12em'}}>Employee Lifecycle</div><h1 style={{margin:'5px 0',fontSize:28}}>Saída & offboarding</h1><p style={{margin:0,color:'rgba(255,255,255,.5)',fontSize:11}}>Encerramento controlado do vínculo, checklist e desativação do acesso.</p></div><div style={{display:'flex',gap:7}}><Button icon={RefreshCw} onClick={load}>Atualizar</Button><Button icon={X} onClick={onClose}>Fechar</Button></div></header>
  {message&&<div style={{marginBottom:12,padding:11,borderRadius:10,border:'1px solid rgba(74,137,255,.2)',background:'rgba(54,112,255,.07)',color:'#a9c4ff',fontSize:9}}>{message}</div>}
  {loading?<div style={{minHeight:450,display:'grid',placeItems:'center',color:'rgba(255,255,255,.45)'}}>A carregar colaboradores…</div>:<div style={{display:'grid',gridTemplateColumns:'320px 1fr',gap:13}}>
    <aside style={{border:'1px solid rgba(255,255,255,.09)',borderRadius:15,padding:10,background:'rgba(255,255,255,.035)',minHeight:600}}><div style={{padding:8,color:'rgba(255,255,255,.45)',fontSize:9,fontWeight:800,textTransform:'uppercase'}}>Colaboradores</div>{employees.map((item)=><button key={item.id} onClick={()=>{setSelected(item);setReason(item.termination_reason||'');setDate(item.termination_date||today());const c=item.offboarding_checklist||{};setChecks({access:Boolean(c.access),documents:Boolean(c.documents),devices:Boolean(c.devices),final:Boolean(c.finalized)});}} style={{width:'100%',display:'flex',alignItems:'center',gap:8,padding:9,marginBottom:4,borderRadius:10,textAlign:'left',border:selected?.id===item.id?'1px solid rgba(73,135,255,.42)':'1px solid transparent',background:selected?.id===item.id?'rgba(60,123,255,.12)':'transparent',color:'#fff'}}><span style={{width:32,height:32,borderRadius:10,display:'grid',placeItems:'center',background:'#e8f1ff',color:'#175bd6',fontSize:9,fontWeight:800}}>{(item.full_name||'TC').split(/\s+/).slice(0,2).map((x)=>x[0]).join('').toUpperCase()}</span><span><strong style={{display:'block',fontSize:9}}>{item.full_name}</strong><small style={{display:'block',marginTop:3,color:'rgba(255,255,255,.4)',fontSize:8}}>{item.status} · {item.employee_code||'—'}</small></span></button>)}</aside>
    <main style={{border:'1px solid rgba(255,255,255,.09)',borderRadius:15,padding:19,background:'rgba(255,255,255,.025)'}}>{selected?<><div style={{display:'flex',alignItems:'center',gap:12,paddingBottom:15,borderBottom:'1px solid rgba(255,255,255,.08)'}}><span style={{width:52,height:52,borderRadius:15,display:'grid',placeItems:'center',background:'#e8f1ff',color:'#175bd6',fontWeight:900}}>{(selected.full_name||'TC').split(/\s+/).slice(0,2).map((x)=>x[0]).join('').toUpperCase()}</span><div><h2 style={{margin:0,fontSize:18}}>{selected.full_name}</h2><small style={{display:'block',marginTop:4,color:'rgba(255,255,255,.45)',fontSize:9}}>{selected.email||'Sem email'} · {selected.status}</small></div></div>
      <div style={{display:'grid',gridTemplateColumns:'1fr 1fr',gap:10,marginTop:16}}><label style={{display:'grid',gap:5,color:'rgba(255,255,255,.55)',fontSize:9}}>Data de saída<input type="date" value={date} onChange={(e)=>setDate(e.target.value)} style={{padding:10,borderRadius:9,border:'1px solid rgba(255,255,255,.11)',background:'rgba(255,255,255,.04)',color:'#fff'}}/></label><label style={{display:'grid',gap:5,color:'rgba(255,255,255,.55)',fontSize:9}}>Motivo<textarea value={reason} onChange={(e)=>setReason(e.target.value)} rows="2" placeholder="Ex.: termo de contrato" style={{padding:10,borderRadius:9,border:'1px solid rgba(255,255,255,.11)',background:'rgba(255,255,255,.04)',color:'#fff'}}/></label></div>
      <section style={{marginTop:17,padding:15,borderRadius:12,border:'1px solid rgba(255,255,255,.08)',background:'rgba(255,255,255,.025)'}}><div style={{display:'flex',alignItems:'center',gap:8,marginBottom:10}}><ClipboardCheck size={16}/><strong style={{fontSize:12}}>Checklist de saída</strong></div>{[['access','Desativar acesso e contas'],['documents','Conferir documentos e arquivo'],['devices','Recolher equipamentos e acessos físicos'],['final','Confirmar entrevista/fecho administrativo']].map(([key,label])=><label key={key} style={{display:'flex',alignItems:'center',gap:9,padding:'10px 0',borderBottom:'1px solid rgba(255,255,255,.06)',fontSize:9}}><input type="checkbox" checked={checks[key]} onChange={(e)=>setChecks((c)=>({...c,[key]:e.target.checked}))}/><span>{label}</span>{checks[key]&&<Check size={14} style={{marginLeft:'auto',color:'#58dba0'}}/>}</label>)}</section>
      <div style={{marginTop:16,padding:11,borderRadius:10,background:'rgba(245,174,55,.07)',color:'#e5bb63',fontSize:8}}><ShieldCheck size={14} style={{verticalAlign:'middle',marginRight:6}}/>Ao concluir, o colaborador passa para INACTIVE e, quando existe conta associada, o perfil de acesso é desativado.</div>
      <div style={{display:'flex',justifyContent:'flex-end',marginTop:14}}><Button primary icon={LogOut} onClick={submit} disabled={busy||selected.status==='INACTIVE'}>{busy?'A processar…':'Confirmar saída'}</Button></div>
    </>:<div style={{minHeight:420,display:'grid',placeItems:'center',color:'rgba(255,255,255,.45)'}}>Selecione um colaborador.</div>}</main>
  </div>}
 </div></div>;
}
