import { useCallback, useEffect, useMemo, useState } from 'react';
import { Award, CheckCircle2, FileText, MessageSquareText, Plus, RefreshCw, Target, TrendingUp, UserRound, X } from 'lucide-react';
import { createClient } from '@supabase/supabase-js';

const supabase = createClient(import.meta.env.VITE_SUPABASE_URL, import.meta.env.VITE_SUPABASE_PUBLISHABLE_KEY, { auth: { persistSession: true, autoRefreshToken: true } });
const ADMIN = new Set(['SUPER_ADMIN', 'COMPANY_ADMIN', 'RH']);
const MANAGERS = new Set(['GESTOR', 'SUPERVISOR']);
const today = () => new Date().toISOString().slice(0, 10);
const date = (value) => value ? new Intl.DateTimeFormat('pt-PT', { day: '2-digit', month: 'short', year: 'numeric' }).format(new Date(value)) : '—';

async function rpc(name, args) { const { data, error } = await supabase.rpc(name, args); if (error) throw error; return data; }
function Button({ children, icon: Icon, variant = 'secondary', onClick, type = 'button' }) { return <button type={type} onClick={onClick} style={{ display: 'inline-flex', alignItems: 'center', justifyContent: 'center', gap: 7, padding: '9px 12px', borderRadius: 9, border: variant === 'primary' ? '1px solid #387cff' : '1px solid rgba(255,255,255,.1)', background: variant === 'primary' ? 'linear-gradient(135deg,#3b7dff,#2459dd)' : 'rgba(255,255,255,.045)', color: '#fff', fontSize: 10, fontWeight: 750 }}>{Icon && <Icon size={15} />}{children}</button>; }
function Modal({ title, onClose, children }) { return <div style={{ position: 'fixed', inset: 0, zIndex: 190, background: 'rgba(4,9,18,.94)', backdropFilter: 'blur(12px)', padding: 24, overflow: 'auto' }}><div style={{ maxWidth: 720, margin: '0 auto', border: '1px solid rgba(255,255,255,.1)', borderRadius: 16, background: '#0e1729', padding: 18 }}><div style={{ display: 'flex', justifyContent: 'space-between', alignItems: 'center', marginBottom: 14 }}><h3 style={{ margin: 0, fontSize: 16 }}>{title}</h3><button onClick={onClose} aria-label="Fechar" style={{ width: 31, height: 31, borderRadius: 8, border: '1px solid rgba(255,255,255,.1)', background: 'transparent', color: '#fff' }}><X size={16} /></button></div>{children}</div></div>; }
function Field({ label, children }) { return <label style={{ display: 'grid', gap: 5, color: 'rgba(255,255,255,.55)', fontSize: 9 }}>{label}{children}</label>; }
const inputStyle = { width: '100%', boxSizing: 'border-box', padding: '9px 10px', borderRadius: 9, border: '1px solid rgba(255,255,255,.11)', background: 'rgba(255,255,255,.04)', color: '#fff', fontSize: 10, outline: 'none' };

export default function PerformanceCenter({ profile, onClose }) {
  const canManage = ADMIN.has(profile?.role);
  const canManager = MANAGERS.has(profile?.role);
  const [employees, setEmployees] = useState([]);
  const [cycles, setCycles] = useState([]);
  const [goals, setGoals] = useState([]);
  const [reviews, setReviews] = useState([]);
  const [feedback, setFeedback] = useState([]);
  const [plans, setPlans] = useState([]);
  const [selectedId, setSelectedId] = useState(null);
  const [loading, setLoading] = useState(true);
  const [modal, setModal] = useState(null);
  const [message, setMessage] = useState('');
  const selected = employees.find((item) => item.id === selectedId) || employees[0] || null;

  const load = useCallback(async () => {
    if (!profile?.company_id) return;
    setLoading(true); setMessage('');
    const [people, cycleResult, goalResult, reviewResult, feedbackResult, planResult] = await Promise.all([
      supabase.from('employees').select('id,full_name,employee_code,status,manager_id').eq('company_id', profile.company_id).order('full_name').limit(2000),
      supabase.from('performance_cycles').select('id,name,year,status,starts_on,ends_on').eq('company_id', profile.company_id).order('year', { ascending: false }).order('created_at', { ascending: false }),
      supabase.from('performance_goals').select('id,employee_id,cycle_id,title,description,target,progress,status,weight,due_date,created_by,created_at,updated_at').eq('company_id', profile.company_id).order('due_date', { ascending: true, nullsFirst: false }).limit(1000),
      supabase.from('performance_reviews').select('id,cycle_id,employee_id,reviewer_id,self_score,manager_score,summary,strengths,development_areas,status,submitted_at,completed_at,updated_at').eq('company_id', profile.company_id).order('updated_at', { ascending: false }).limit(1000),
      supabase.from('performance_feedback').select('id,employee_id,author_user_id,kind,message,created_at').eq('company_id', profile.company_id).order('created_at', { ascending: false }).limit(1000),
      supabase.from('performance_development_plans').select('id,employee_id,cycle_id,title,action,owner,due_date,status,created_by,created_at,updated_at').eq('company_id', profile.company_id).order('due_date', { ascending: true, nullsFirst: false }).limit(1000),
    ]);
    const firstError = [people, cycleResult, goalResult, reviewResult, feedbackResult, planResult].find((result) => result.error)?.error;
    if (firstError) setMessage(firstError.message || 'Não foi possível sincronizar o módulo.');
    setEmployees(people.data || []); setCycles(cycleResult.data || []); setGoals(goalResult.data || []); setReviews(reviewResult.data || []); setFeedback(feedbackResult.data || []); setPlans(planResult.data || []);
    if (!selectedId && people.data?.[0]?.id) setSelectedId(people.data[0].id);
    setLoading(false);
  }, [profile?.company_id, selectedId]);
  useEffect(() => { load(); }, [load]);

  const scopedEmployees = canManage ? employees : canManager ? employees.filter((e) => e.manager_id === profile.employee_id || e.id === profile.employee_id) : employees.filter((e) => e.id === profile.employee_id);
  const person = selected || scopedEmployees[0] || null;
  const personGoals = useMemo(() => goals.filter((g) => g.employee_id === person?.id), [goals, person?.id]);
  const personReviews = useMemo(() => reviews.filter((r) => r.employee_id === person?.id), [reviews, person?.id]);
  const personFeedback = useMemo(() => feedback.filter((f) => f.employee_id === person?.id), [feedback, person?.id]);
  const personPlans = useMemo(() => plans.filter((p) => p.employee_id === person?.id), [plans, person?.id]);
  const avgGoal = personGoals.length ? Math.round(personGoals.reduce((sum, g) => sum + Number(g.progress || 0), 0) / personGoals.length) : 0;

  const submit = async (type, form) => {
    try {
      if (type === 'cycle') await rpc('create_performance_cycle', { p_name: form.name, p_year: Number(form.year), p_starts_on: form.starts_on || null, p_ends_on: form.ends_on || null, p_status: form.status });
      if (type === 'goal') await rpc('save_performance_goal', { p_employee_id: form.employee_id || person?.id, p_cycle_id: form.cycle_id || null, p_title: form.title, p_description: form.description, p_target: form.target, p_progress: Number(form.progress), p_status: form.status, p_weight: Number(form.weight), p_due_date: form.due_date || null });
      if (type === 'feedback') await rpc('add_performance_feedback', { p_employee_id: form.employee_id || person?.id, p_kind: form.kind, p_message: form.message });
      if (type === 'review') await rpc('save_performance_review', { p_review_id: form.review_id || null, p_cycle_id: form.cycle_id, p_employee_id: form.employee_id || person?.id, p_self_score: form.self_score === '' ? null : Number(form.self_score), p_manager_score: form.manager_score === '' ? null : Number(form.manager_score), p_summary: form.summary, p_strengths: form.strengths, p_development_areas: form.development_areas, p_status: form.status });
      if (type === 'plan') await rpc('save_development_plan', { p_plan_id: null, p_employee_id: form.employee_id || person?.id, p_cycle_id: form.cycle_id || null, p_title: form.title, p_action: form.action, p_owner: form.owner, p_due_date: form.due_date || null, p_status: form.status });
      setModal(null); setMessage('Alteração guardada com sucesso.'); await load();
    } catch (error) { setMessage(error.message || 'Não foi possível concluir a operação.'); }
  };

  if (loading) return <div style={{ position: 'fixed', inset: 0, zIndex: 190, background: '#07101f', color: '#fff', display: 'grid', placeItems: 'center' }}>A preparar gestão de performance…</div>;
  return <div style={{ position: 'fixed', inset: 0, zIndex: 190, overflow: 'auto', background: '#07101f', color: '#fff', padding: 24 }}>
    <div style={{ maxWidth: 1440, margin: '0 auto' }}>
      <header style={{ display: 'flex', justifyContent: 'space-between', alignItems: 'flex-end', gap: 15, marginBottom: 17 }}><div><div style={{ color: '#71a5ff', fontSize: 10, textTransform: 'uppercase', fontWeight: 800, letterSpacing: '.12em' }}>People Development</div><h1 style={{ margin: '6px 0', fontSize: 28 }}>Performance & carreira</h1><p style={{ margin: 0, color: 'rgba(255,255,255,.5)', fontSize: 11 }}>Objetivos, avaliações, feedback e planos de desenvolvimento num ciclo contínuo.</p></div><div style={{ display: 'flex', gap: 7 }}><Button icon={RefreshCw} onClick={load}>Sincronizar</Button>{canManage && <Button icon={Plus} onClick={() => setModal({ type: 'cycle' })}>Novo ciclo</Button>}<button onClick={onClose} style={{ padding: '9px 12px', borderRadius: 9, border: '1px solid rgba(255,255,255,.1)', background: 'rgba(255,255,255,.04)', color: '#fff' }}>Fechar</button></div></header>
      {message && <div style={{ marginBottom: 12, padding: 11, borderRadius: 10, border: '1px solid rgba(93,150,255,.2)', background: 'rgba(55,112,255,.08)', color: '#a9c4ff', fontSize: 9 }}>{message}</div>}
      <div style={{ display: 'grid', gridTemplateColumns: '280px 1fr', gap: 13 }}>
        <aside style={{ border: '1px solid rgba(255,255,255,.09)', borderRadius: 15, background: 'rgba(255,255,255,.035)', padding: 10, minHeight: 650 }}><div style={{ padding: 8, color: 'rgba(255,255,255,.45)', fontSize: 9, fontWeight: 800, textTransform: 'uppercase' }}>Pessoas</div>{scopedEmployees.map((item) => <button key={item.id} onClick={() => setSelectedId(item.id)} style={{ width: '100%', display: 'flex', alignItems: 'center', gap: 8, padding: 9, marginBottom: 4, textAlign: 'left', borderRadius: 10, border: selectedId === item.id ? '1px solid rgba(71,133,255,.4)' : '1px solid transparent', background: selectedId === item.id ? 'rgba(62,123,255,.12)' : 'transparent', color: '#fff' }}><span style={{ width: 31, height: 31, borderRadius: 9, display: 'grid', placeItems: 'center', background: '#e7efff', color: '#1d5bd4', fontSize: 8, fontWeight: 850 }}>{(item.full_name || 'TC').split(/\s+/).slice(0, 2).map((x) => x[0]).join('').toUpperCase()}</span><span style={{ minWidth: 0 }}><strong style={{ display: 'block', fontSize: 9 }}>{item.full_name}</strong><small style={{ display: 'block', marginTop: 3, color: 'rgba(255,255,255,.43)', fontSize: 8 }}>{item.employee_code || 'Sem código'}</small></span></button>)}</aside>
        <main>
          <section style={{ border: '1px solid rgba(255,255,255,.09)', borderRadius: 15, background: 'linear-gradient(135deg,rgba(24,51,98,.65),rgba(12,20,38,.92))', padding: 19, marginBottom: 12 }}><div style={{ display: 'flex', justifyContent: 'space-between', gap: 15, alignItems: 'center' }}><div style={{ display: 'flex', alignItems: 'center', gap: 12 }}><div style={{ width: 56, height: 56, borderRadius: 15, display: 'grid', placeItems: 'center', background: '#e7efff', color: '#175bd6', fontWeight: 900 }}>{person ? person.full_name.split(/\s+/).slice(0,2).map((x) => x[0]).join('').toUpperCase() : 'TC'}</div><div><h2 style={{ margin: 0, fontSize: 18 }}>{person?.full_name || 'Colaborador'}</h2><p style={{ margin: '4px 0 0', color: 'rgba(255,255,255,.5)', fontSize: 9 }}>{person?.employee_code || '—'} · {person?.status || '—'}</p></div></div><div style={{ display: 'flex', gap: 7 }}><Button icon={Target} onClick={() => setModal({ type: 'goal' })}>Objetivo</Button><Button icon={MessageSquareText} onClick={() => setModal({ type: 'feedback' })}>Feedback</Button><Button icon={FileText} onClick={() => setModal({ type: 'review' })}>Avaliação</Button><Button icon={TrendingUp} onClick={() => setModal({ type: 'plan' })}>PDI</Button></div></div></section>
          <div style={{ display: 'grid', gridTemplateColumns: 'repeat(4,minmax(0,1fr))', gap: 9, marginBottom: 12 }}><Kpi label="Objetivos" value={`${avgGoal}%`} icon={Target} helper={`${personGoals.length} registados`} /><Kpi label="Avaliações" value={personReviews.length} icon={Award} helper="histórico" /><Kpi label="Feedback" value={personFeedback.length} icon={MessageSquareText} helper="registos" /><Kpi label="PDI" value={personPlans.filter((p) => p.status !== 'DONE').length} icon={TrendingUp} helper="ações abertas" /></div>
          <div style={{ display: 'grid', gridTemplateColumns: '1.1fr .9fr', gap: 12 }}>
            <section style={{ border: '1px solid rgba(255,255,255,.09)', borderRadius: 14, padding: 17, background: 'rgba(255,255,255,.03)' }}><h3 style={{ margin: 0, fontSize: 13 }}>Objetivos</h3>{personGoals.map((goal) => <div key={goal.id} style={{ padding: '11px 0', borderBottom: '1px solid rgba(255,255,255,.06)' }}><div style={{ display: 'flex', justifyContent: 'space-between', gap: 10 }}><strong style={{ fontSize: 10 }}>{goal.title}</strong><span style={{ fontSize: 9 }}>{Number(goal.progress || 0)}%</span></div><div style={{ height: 6, background: 'rgba(255,255,255,.08)', borderRadius: 99, overflow: 'hidden', marginTop: 6 }}><span style={{ display: 'block', height: '100%', width: `${Math.min(100, Math.max(0, Number(goal.progress || 0)))}%`, background: '#4c89ff' }} /></div><small style={{ display: 'block', marginTop: 5, color: 'rgba(255,255,255,.4)', fontSize: 8 }}>{goal.status} · prazo {date(goal.due_date)} · peso {goal.weight}%</small></div>)}{!personGoals.length && <div style={{ padding: 30, textAlign: 'center', color: 'rgba(255,255,255,.4)', fontSize: 9 }}>Nenhum objetivo registado.</div>}</section>
            <section style={{ display: 'grid', gap: 12 }}><div style={{ border: '1px solid rgba(255,255,255,.09)', borderRadius: 14, padding: 17, background: 'rgba(255,255,255,.03)' }}><h3 style={{ margin: 0, fontSize: 13 }}>Ciclos</h3>{cycles.slice(0,5).map((cycle) => <div key={cycle.id} style={{ display: 'flex', justifyContent: 'space-between', padding: '9px 0', borderBottom: '1px solid rgba(255,255,255,.06)' }}><div><strong style={{ fontSize: 9 }}>{cycle.name}</strong><small style={{ display: 'block', marginTop: 3, color: 'rgba(255,255,255,.4)', fontSize: 8 }}>{cycle.year} · {date(cycle.starts_on)} → {date(cycle.ends_on)}</small></div><span style={{ fontSize: 8 }}>{cycle.status}</span></div>)}</div><div style={{ border: '1px solid rgba(255,255,255,.09)', borderRadius: 14, padding: 17, background: 'rgba(255,255,255,.03)' }}><h3 style={{ margin: 0, fontSize: 13 }}>PDI e feedback</h3>{personPlans.slice(0,4).map((plan) => <div key={plan.id} style={{ padding: '8px 0', borderBottom: '1px solid rgba(255,255,255,.06)' }}><strong style={{ fontSize: 9 }}>{plan.title}</strong><small style={{ display: 'block', color: 'rgba(255,255,255,.42)', fontSize: 8 }}>{plan.action} · {plan.status}</small></div>)}{personFeedback.slice(0,3).map((item) => <div key={item.id} style={{ padding: '8px 0', borderBottom: '1px solid rgba(255,255,255,.06)' }}><strong style={{ fontSize: 8 }}>{item.kind}</strong><p style={{ margin: '3px 0 0', fontSize: 8, color: 'rgba(255,255,255,.58)' }}>{item.message}</p></div>)}</div></section>
          </div>
          <section style={{ marginTop: 12, border: '1px solid rgba(255,255,255,.09)', borderRadius: 14, padding: 17, background: 'rgba(255,255,255,.03)' }}><h3 style={{ margin: 0, fontSize: 13 }}>Avaliações</h3>{personReviews.slice(0,8).map((review) => <div key={review.id} style={{ display: 'grid', gridTemplateColumns: '120px 90px 90px 1fr', gap: 10, alignItems: 'center', padding: '10px 0', borderBottom: '1px solid rgba(255,255,255,.06)' }}><span style={{ fontSize: 8 }}>{date(review.updated_at)}</span><strong style={{ fontSize: 9 }}>Auto: {review.self_score ?? '—'}</strong><strong style={{ fontSize: 9 }}>Gestor: {review.manager_score ?? '—'}</strong><span style={{ fontSize: 8, color: 'rgba(255,255,255,.5)' }}>{review.status} · {review.summary || 'Sem síntese'}</span></div>)}</section>
        </main>
      </div>
    </div>
    {modal?.type === 'cycle' && <Modal title="Novo ciclo de performance" onClose={() => setModal(null)}><form onSubmit={(e) => { e.preventDefault(); const f = new FormData(e.currentTarget); submit('cycle', Object.fromEntries(f.entries())); }} style={{ display: 'grid', gap: 10 }}><Field label="Nome"><input name="name" required defaultValue={`Ciclo ${new Date().getFullYear()}`} style={inputStyle} /></Field><div style={{ display: 'grid', gridTemplateColumns: '1fr 1fr', gap: 10 }}><Field label="Ano"><input name="year" type="number" min="2000" max="2100" defaultValue={new Date().getFullYear()} style={inputStyle} /></Field><Field label="Estado"><select name="status" defaultValue="OPEN" style={inputStyle}><option>DRAFT</option><option>OPEN</option><option>CLOSED</option></select></Field></div><div style={{ display: 'grid', gridTemplateColumns: '1fr 1fr', gap: 10 }}><Field label="Início"><input name="starts_on" type="date" defaultValue={today()} style={inputStyle} /></Field><Field label="Fim"><input name="ends_on" type="date" style={inputStyle} /></Field></div><Button variant="primary" type="submit" icon={CheckCircle2}>Criar ciclo</Button></form></Modal>}
    {modal?.type === 'goal' && <Modal title={`Novo objetivo · ${person?.full_name || ''}`} onClose={() => setModal(null)}><form onSubmit={(e) => { e.preventDefault(); const f = new FormData(e.currentTarget); submit('goal', Object.fromEntries(f.entries())); }} style={{ display: 'grid', gap: 10 }}><Field label="Título"><input name="title" required style={inputStyle} /></Field><Field label="Descrição"><textarea name="description" rows="3" style={inputStyle} /></Field><Field label="Meta"><input name="target" placeholder="Ex.: reduzir atrasos em 20%" style={inputStyle} /></Field><div style={{ display: 'grid', gridTemplateColumns: '1fr 1fr', gap: 10 }}><Field label="Ciclo"><select name="cycle_id" style={inputStyle}><option value="">Sem ciclo</option>{cycles.filter((c) => c.status !== 'CLOSED').map((c) => <option key={c.id} value={c.id}>{c.name}</option>)}</select></Field><Field label="Prazo"><input name="due_date" type="date" style={inputStyle} /></Field><Field label="Progresso"><input name="progress" type="number" min="0" max="100" defaultValue="0" style={inputStyle} /></Field><Field label="Peso"><input name="weight" type="number" min="1" max="100" defaultValue="100" style={inputStyle} /></Field></div><Field label="Estado"><select name="status" defaultValue="PLANNED" style={inputStyle}><option>PLANNED</option><option>ON_TRACK</option><option>AT_RISK</option><option>COMPLETED</option></select></Field><Button variant="primary" type="submit" icon={Target}>Guardar objetivo</Button></form></Modal>}
    {modal?.type === 'feedback' && <Modal title={`Novo feedback · ${person?.full_name || ''}`} onClose={() => setModal(null)}><form onSubmit={(e) => { e.preventDefault(); const f = new FormData(e.currentTarget); submit('feedback', Object.fromEntries(f.entries())); }} style={{ display: 'grid', gap: 10 }}><Field label="Tipo"><select name="kind" defaultValue="GENERAL" style={inputStyle}><option>GENERAL</option><option>PRAISE</option><option>CONSTRUCTIVE</option></select></Field><Field label="Mensagem"><textarea name="message" required rows="6" style={inputStyle} /></Field><Button variant="primary" type="submit" icon={MessageSquareText}>Registar feedback</Button></form></Modal>}
    {modal?.type === 'review' && <Modal title={`Avaliação · ${person?.full_name || ''}`} onClose={() => setModal(null)}><form onSubmit={(e) => { e.preventDefault(); const f = new FormData(e.currentTarget); submit('review', Object.fromEntries(f.entries())); }} style={{ display: 'grid', gap: 10 }}><Field label="Ciclo"><select name="cycle_id" required style={inputStyle}><option value="">Selecionar</option>{cycles.filter((c) => c.status !== 'CLOSED').map((c) => <option key={c.id} value={c.id}>{c.name}</option>)}</select></Field><div style={{ display: 'grid', gridTemplateColumns: '1fr 1fr', gap: 10 }}><Field label="Autoavaliação (0-100)"><input name="self_score" type="number" min="0" max="100" style={inputStyle} /></Field><Field label="Avaliação gestor (0-100)"><input name="manager_score" type="number" min="0" max="100" style={inputStyle} /></Field></div><Field label="Síntese"><textarea name="summary" rows="4" style={inputStyle} /></Field><Field label="Pontos fortes"><textarea name="strengths" rows="3" style={inputStyle} /></Field><Field label="Áreas de desenvolvimento"><textarea name="development_areas" rows="3" style={inputStyle} /></Field><Field label="Estado"><select name="status" defaultValue="IN_REVIEW" style={inputStyle}><option>DRAFT</option><option>SELF_REVIEW</option><option>IN_REVIEW</option><option>COMPLETED</option></select></Field><Button variant="primary" type="submit" icon={FileText}>Guardar avaliação</Button></form></Modal>}
    {modal?.type === 'plan' && <Modal title={`Plano de desenvolvimento · ${person?.full_name || ''}`} onClose={() => setModal(null)}><form onSubmit={(e) => { e.preventDefault(); const f = new FormData(e.currentTarget); submit('plan', Object.fromEntries(f.entries())); }} style={{ display: 'grid', gap: 10 }}><Field label="Título"><input name="title" required style={inputStyle} /></Field><Field label="Ação"><textarea name="action" required rows="4" style={inputStyle} /></Field><div style={{ display: 'grid', gridTemplateColumns: '1fr 1fr', gap: 10 }}><Field label="Responsável"><input name="owner" style={inputStyle} /></Field><Field label="Prazo"><input name="due_date" type="date" style={inputStyle} /></Field></div><Field label="Estado"><select name="status" defaultValue="PLANNED" style={inputStyle}><option>PLANNED</option><option>IN_PROGRESS</option><option>DONE</option><option>CANCELLED</option></select></Field><Button variant="primary" type="submit" icon={TrendingUp}>Criar PDI</Button></form></Modal>}
  </div>;
}
function Kpi({ label, value, helper, icon: Icon }) { return <div style={{ border: '1px solid rgba(255,255,255,.08)', borderRadius: 13, padding: 13, background: 'rgba(255,255,255,.03)' }}><div style={{ display: 'flex', justifyContent: 'space-between', color: 'rgba(255,255,255,.5)', fontSize: 9 }}><span>{label}</span><Icon size={14} /></div><strong style={{ display: 'block', marginTop: 14, fontSize: 22 }}>{value}</strong><small style={{ color: 'rgba(255,255,255,.4)', fontSize: 8 }}>{helper}</small></div>; }
