import { useCallback, useEffect, useState } from 'react';
import { CheckCircle2, Copy, KeyRound, Link2, Plus, RefreshCw, Send, ShieldCheck, Trash2, X } from 'lucide-react';
import { createClient } from '@supabase/supabase-js';

const supabase = createClient(import.meta.env.VITE_SUPABASE_URL, import.meta.env.VITE_SUPABASE_PUBLISHABLE_KEY, { auth: { persistSession: true, autoRefreshToken: true } });
const API_URL = `${import.meta.env.VITE_SUPABASE_URL}/functions/v1/teconnect-api`;

function Button({ children, icon: Icon, onClick, primary = false, danger = false, disabled = false }) { return <button type="button" onClick={onClick} disabled={disabled} style={{ display:'inline-flex',alignItems:'center',justifyContent:'center',gap:7,padding:'9px 12px',borderRadius:9,border:danger?'1px solid rgba(239,103,123,.3)':primary?'1px solid #3d82ff':'1px solid rgba(255,255,255,.1)',background:danger?'rgba(239,103,123,.08)':primary?'linear-gradient(135deg,#3f82ff,#2459dd)':'rgba(255,255,255,.045)',color:'#fff',fontSize:9,opacity:disabled?.55:1 }}>{Icon&&<Icon size={14}/>} {children}</button>; }
function Panel({ title, icon: Icon, children, actions }) { return <section style={{border:'1px solid rgba(255,255,255,.09)',borderRadius:15,background:'rgba(255,255,255,.035)',padding:17}}><div style={{display:'flex',justifyContent:'space-between',alignItems:'center',gap:10,marginBottom:14}}><div style={{display:'flex',alignItems:'center',gap:8}}><Icon size={16}/><h2 style={{margin:0,fontSize:13}}>{title}</h2></div><div style={{display:'flex',gap:7}}>{actions}</div></div>{children}</section>; }
const inputStyle={width:'100%',boxSizing:'border-box',padding:'9px 10px',borderRadius:9,border:'1px solid rgba(255,255,255,.12)',background:'rgba(255,255,255,.045)',color:'#fff',fontSize:10};

export default function IntegrationsCenter({ profile, onClose }) {
  const [keys,setKeys]=useState([]); const [webhooks,setWebhooks]=useState([]); const [deliveries,setDeliveries]=useState([]); const [loading,setLoading]=useState(true); const [message,setMessage]=useState(''); const [modal,setModal]=useState(null); const [newSecret,setNewSecret]=useState('');
  const load=useCallback(async()=>{if(!profile?.company_id)return;setLoading(true);setMessage('');const [k,w,d]=await Promise.all([supabase.from('app_api_keys').select('id,name,key_prefix,active,created_at,last_used_at,expires_at,revoked_at').eq('company_id',profile.company_id).order('created_at',{ascending:false}),supabase.from('webhook_endpoints').select('id,name,url,events,active,created_at,last_delivery_at,last_status').eq('company_id',profile.company_id).order('created_at',{ascending:false}),supabase.from('webhook_deliveries').select('id,endpoint_id,event_type,status,http_status,response_excerpt,attempt,created_at,delivered_at').eq('company_id',profile.company_id).order('created_at',{ascending:false}).limit(100)]);const firstError=[k,w,d].find((r)=>r.error)?.error;if(firstError)setMessage(firstError.message);setKeys(k.data||[]);setWebhooks(w.data||[]);setDeliveries(d.data||[]);setLoading(false);},[profile?.company_id]);
  useEffect(()=>{load();},[load]);
  const createKey=async()=>{const name=modal?.name?.trim();if(!name)return;const {data,error}=await supabase.rpc('create_api_key_app',{p_name:name,p_expires_at:modal?.expires_at?new Date(modal.expires_at).toISOString():null});if(error)setMessage(error.message);else{setNewSecret(data?.secret||'');setModal({type:'secret',title:'Chave API criada',secret:data?.secret||''});await load();}};
  const createWebhook=async()=>{const name=modal?.name?.trim();const url=modal?.url?.trim();if(!name||!url)return;const events=String(modal?.events||'employee.created,employee.updated').split(',').map((x)=>x.trim()).filter(Boolean);const {data,error}=await supabase.rpc('create_webhook_endpoint_app',{p_name:name,p_url:url,p_events:events});if(error)setMessage(error.message);else{setModal({type:'secret-webhook',title:'Webhook criado',secret:data?.secret||'',url:data?.url||url});await load();}};
  const revokeKey=async(id)=>{const {error}=await supabase.rpc('revoke_api_key_app',{p_id:id});if(error)setMessage(error.message);else await load();};
  const revokeWebhook=async(id)=>{const {error}=await supabase.rpc('revoke_webhook_endpoint_app',{p_id:id});if(error)setMessage(error.message);else await load();};
  const testWebhook=async(endpoint)=>{setMessage('A enviar teste…');const {data,error}=await supabase.functions.invoke('teconnect-webhook-deliver',{body:{endpoint_id:endpoint.id,event_type:endpoint.events?.[0]||'employee.created',payload:{source:'te-connect',test:true,company_id:profile.company_id}}});if(error)setMessage(error.message);else setMessage(data?.ok?'Webhook entregue com sucesso.':`Webhook devolveu ${data?.http_status||'erro'}`);await load();};
  const copy=async(text)=>{try{await navigator.clipboard.writeText(text);setMessage('Copiado.');}catch{setMessage('Não foi possível copiar automaticamente.');}};
  return <div style={{position:'fixed',inset:0,zIndex:190,overflow:'auto',background:'#07101f',color:'#fff',padding:24}}><div style={{maxWidth:1250,margin:'0 auto'}}>
    <header style={{display:'flex',justifyContent:'space-between',alignItems:'flex-end',gap:15,marginBottom:16}}><div><div style={{color:'#73a7ff',fontSize:10,fontWeight:800,textTransform:'uppercase',letterSpacing:'.12em'}}>Enterprise Integrations</div><h1 style={{margin:'5px 0',fontSize:28}}>API & Webhooks</h1><p style={{margin:0,color:'rgba(255,255,255,.5)',fontSize:11}}>Conecte o Te-connect a ERP, folha, BI e aplicações internas.</p></div><div style={{display:'flex',gap:7}}><Button icon={RefreshCw} onClick={load}>Atualizar</Button><Button icon={X} onClick={onClose}>Fechar</Button></div></header>
    {message&&<div style={{marginBottom:12,padding:10,borderRadius:10,border:'1px solid rgba(79,138,255,.2)',background:'rgba(58,121,255,.07)',color:'#aec5ff',fontSize:9}}>{message}</div>}
    {loading?<div style={{minHeight:450,display:'grid',placeItems:'center',color:'rgba(255,255,255,.45)'}}>A carregar integrações…</div>:<div style={{display:'grid',gap:12}}>
      <Panel title="API do Te-connect" icon={KeyRound} actions={<Button primary icon={Plus} onClick={()=>setModal({type:'create-key'})}>Nova chave API</Button>}><div style={{padding:12,borderRadius:10,background:'rgba(255,255,255,.025)',border:'1px solid rgba(255,255,255,.07)'}}><div style={{fontSize:8,color:'rgba(255,255,255,.4)',textTransform:'uppercase'}}>Base URL</div><div style={{display:'flex',gap:7,alignItems:'center',marginTop:6}}><code style={{flex:1,fontSize:9,color:'#b9ceff',overflow:'auto'}}>{API_URL}</code><Button icon={Copy} onClick={()=>copy(API_URL)}>Copiar</Button></div><p style={{margin:'8px 0 0',color:'rgba(255,255,255,.42)',fontSize:8}}>Use o cabeçalho <strong>X-Teconnect-Api-Key</strong>. Endpoints ativos: <strong>/v1/health</strong>, <strong>/v1/employees</strong>, <strong>/v1/attendance</strong>.</p></div><div style={{marginTop:11,display:'grid',gap:7}}>{keys.map((key)=><div key={key.id} style={{display:'grid',gridTemplateColumns:'1fr auto',gap:10,alignItems:'center',padding:11,border:'1px solid rgba(255,255,255,.07)',borderRadius:10}}><div><strong style={{display:'block',fontSize:10}}>{key.name}</strong><small style={{display:'block',marginTop:4,color:'rgba(255,255,255,.45)',fontSize:8}}>{key.key_prefix}••• · criada {new Date(key.created_at).toLocaleDateString('pt-PT')} · {key.active?'ativa':'revogada'}</small></div><div style={{display:'flex',gap:7}}>{key.active&&<Button danger icon={Trash2} onClick={()=>revokeKey(key.id)}>Revogar</Button>}</div></div>)}{!keys.length&&<div style={{padding:25,color:'rgba(255,255,255,.45)',fontSize:9}}>Ainda não existem chaves API.</div>}</div></Panel>
      <Panel title="Webhooks" icon={Link2} actions={<Button primary icon={Plus} onClick={()=>setModal({type:'create-webhook'})}>Novo webhook</Button>}><div style={{display:'grid',gap:7}}>{webhooks.map((hook)=><div key={hook.id} style={{display:'grid',gridTemplateColumns:'1fr auto',gap:10,alignItems:'center',padding:11,border:'1px solid rgba(255,255,255,.07)',borderRadius:10}}><div><strong style={{display:'block',fontSize:10}}>{hook.name}</strong><small style={{display:'block',marginTop:4,color:'rgba(255,255,255,.45)',fontSize:8,wordBreak:'break-all'}}>{hook.url}</small><small style={{display:'block',marginTop:4,color:'rgba(255,255,255,.35)',fontSize:8}}>{hook.active?'ativo':'inativo'} · eventos: {(hook.events||[]).join(', ')} · último {hook.last_status||'—'}</small></div><div style={{display:'flex',gap:7}}>{hook.active&&<Button icon={Send} onClick={()=>testWebhook(hook)}>Teste</Button>}{hook.active&&<Button danger icon={Trash2} onClick={()=>revokeWebhook(hook.id)}>Desativar</Button>}</div></div>)}{!webhooks.length&&<div style={{padding:25,color:'rgba(255,255,255,.45)',fontSize:9}}>Ainda não existem endpoints.</div>}</div></Panel>
      <Panel title="Entregas recentes" icon={Send}><div style={{display:'grid',gap:6}}>{deliveries.slice(0,20).map((delivery)=><div key={delivery.id} style={{display:'grid',gridTemplateColumns:'170px 1fr 90px 80px',gap:9,alignItems:'center',padding:'8px 0',borderBottom:'1px solid rgba(255,255,255,.06)',fontSize:8}}><span>{delivery.event_type}</span><span style={{color:'rgba(255,255,255,.45)',overflow:'hidden',textOverflow:'ellipsis',whiteSpace:'nowrap'}}>{delivery.response_excerpt||'—'}</span><strong style={{color:delivery.status==='DELIVERED'?'#5edaa2':'#f08e9e'}}>{delivery.status}</strong><span>{delivery.http_status||'—'}</span></div>)}{!deliveries.length&&<div style={{padding:25,color:'rgba(255,255,255,.45)'}}>Sem entregas registadas.</div>}</div></Panel>
      <div style={{display:'flex',alignItems:'center',gap:8,color:'rgba(255,255,255,.42)',fontSize:8}}><ShieldCheck size={14}/> Segredos são apresentados apenas no momento da criação. Chaves API nunca guardam o valor bruto, apenas o hash para autenticação.</div>
    </div>}
    {modal?.type==='create-key'&&<Modal title="Nova chave API" onClose={()=>setModal(null)}><label style={label}>Nome<input value={modal.name||''} onChange={(e)=>setModal((m)=>({...m,name:e.target.value}))} placeholder="ERP Produção" style={inputStyle}/></label><label style={label}>Expiração opcional<input type="datetime-local" value={modal.expires_at||''} onChange={(e)=>setModal((m)=>({...m,expires_at:e.target.value}))} style={inputStyle}/></label><div style={{display:'flex',justifyContent:'flex-end',marginTop:13}}><Button primary onClick={createKey}>Criar chave</Button></div></Modal>}
    {modal?.type==='create-webhook'&&<Modal title="Novo webhook" onClose={()=>setModal(null)}><label style={label}>Nome<input value={modal.name||''} onChange={(e)=>setModal((m)=>({...m,name:e.target.value}))} placeholder="ERP / Integração RH" style={inputStyle}/></label><label style={label}>URL HTTPS<input value={modal.url||''} onChange={(e)=>setModal((m)=>({...m,url:e.target.value}))} placeholder="https://erp.empresa.pt/webhooks/te-connect" style={inputStyle}/></label><label style={label}>Eventos separados por vírgula<input value={modal.events||'employee.created,employee.updated,attendance.updated'} onChange={(e)=>setModal((m)=>({...m,events:e.target.value}))} style={inputStyle}/></label><div style={{display:'flex',justifyContent:'flex-end',marginTop:13}}><Button primary onClick={createWebhook}>Criar webhook</Button></div></Modal>}
    {(modal?.type==='secret'||modal?.type==='secret-webhook')&&<Modal title={modal.title} onClose={()=>setModal(null)}><div style={{padding:12,borderRadius:10,background:'rgba(39,201,132,.06)',border:'1px solid rgba(39,201,132,.18)',color:'#9af0c6',fontSize:9}}>Guarde este segredo agora. Por segurança, o Te-connect não o mostra novamente.</div><div style={{display:'flex',gap:7,marginTop:12}}><input readOnly value={modal.secret||newSecret} style={{...inputStyle,textAlign:'left',letterSpacing:'.05em'}}/><Button icon={Copy} onClick={()=>copy(modal.secret||newSecret)}>Copiar</Button></div>{modal?.url&&<div style={{marginTop:10,fontSize:8,color:'rgba(255,255,255,.45)'}}>Endpoint: {modal.url}</div>}</Modal>}
  </div></div>;
}
function Modal({title,onClose,children}){return <div style={{position:'fixed',inset:0,zIndex:250,background:'rgba(4,9,18,.92)',backdropFilter:'blur(12px)',display:'grid',placeItems:'center',padding:20}}><div style={{width:'min(620px,100%)',border:'1px solid rgba(255,255,255,.1)',borderRadius:15,background:'#0e1729',padding:17}}><div style={{display:'flex',justifyContent:'space-between',alignItems:'center',marginBottom:13}}><strong style={{fontSize:14}}>{title}</strong><button onClick={onClose} style={{width:31,height:31,borderRadius:8,border:'1px solid rgba(255,255,255,.1)',background:'transparent',color:'#fff'}}><X size={16}/></button></div>{children}</div></div>}
const label={display:'grid',gap:5,fontSize:9,color:'rgba(255,255,255,.55)',marginBottom:10};
