import { useCallback, useEffect, useState } from 'react';
import { Download, FileJson, FileSpreadsheet, LockKeyhole, RefreshCw, ShieldCheck, UserRound, X } from 'lucide-react';
import { createClient } from '@supabase/supabase-js';

const supabase = createClient(import.meta.env.VITE_SUPABASE_URL, import.meta.env.VITE_SUPABASE_PUBLISHABLE_KEY, { auth: { persistSession: true, autoRefreshToken: true } });

function Button({children,icon:Icon,onClick,primary=false}){return <button type="button" onClick={onClick} style={{display:'inline-flex',alignItems:'center',justifyContent:'center',gap:7,padding:'9px 12px',borderRadius:9,border:primary?'1px solid #3e82ff':'1px solid rgba(255,255,255,.1)',background:primary?'linear-gradient(135deg,#3f82ff,#2459dd)':'rgba(255,255,255,.045)',color:'#fff',fontSize:9}}>{Icon&&<Icon size={14}/>} {children}</button>}
const saveFile=(name,content,type)=>{const blob=new Blob([content],{type});const url=URL.createObjectURL(blob);const a=document.createElement('a');a.href=url;a.download=name;a.click();URL.revokeObjectURL(url)};

export default function PrivacyCenter({profile,onClose}){
 const [loading,setLoading]=useState(true);const [data,setData]=useState(null);const [message,setMessage]=useState('');
 const admin=['SUPER_ADMIN','COMPANY_ADMIN','RH'].includes(profile?.role);
 const load=useCallback(async()=>{setLoading(true);setMessage('');try{if(admin){const [employees,documents,training,goals]=await Promise.all([supabase.from('employees').select('id,employee_code,full_name,email,phone,department_id,position_id,hire_date,status').eq('company_id',profile.company_id).order('full_name').limit(5000),supabase.from('employee_documents').select('id,employee_id,document_type,title,issued_at,expires_at,status,created_at').eq('company_id',profile.company_id).limit(5000),supabase.from('employee_trainings').select('id,employee_id,course_id,status,started_at,completed_at,score,created_at').eq('company_id',profile.company_id).limit(5000),supabase.from('performance_goals').select('id,employee_id,title,progress,status,due_date,created_at').eq('company_id',profile.company_id).limit(5000)]);setData({employees:employees.data||[],documents:documents.data||[],training:training.data||[],goals:goals.data||[]});const first=[employees,documents,training,goals].find(r=>r.error)?.error;if(first)setMessage(first.message)}else{const {data:summary,error}=await supabase.rpc('get_people_performance_summary',{p_employee_id:null});if(error)throw error;setData(summary||{})}}catch(e){setMessage(e.message||'Não foi possível preparar os dados.')}finally{setLoading(false)}},[profile?.company_id,profile?.role,admin]);
 useEffect(()=>{load()},[load]);
 const exportJson=()=>saveFile(`te-connect-dados-${new Date().toISOString().slice(0,10)}.json`,JSON.stringify({exported_at:new Date().toISOString(),company_id:admin?profile.company_id:undefined,data},null,2),'application/json;charset=utf-8');
 const exportCsv=()=>{const rows=admin?(data?.employees||[]):data?.employee?[data.employee]:[];const header=['id','employee_code','full_name','email','phone','hire_date','status'];const csv=[header,...rows.map((r)=>header.map((k)=>r?.[k]??''))].map((r)=>r.map((v)=>`"${String(v).replaceAll('"','""')}"`).join(';')).join('\n');saveFile(`te-connect-colaboradores-${new Date().toISOString().slice(0,10)}.csv`,`\ufeff${csv}`,'text/csv;charset=utf-8')};
 return <div style={{position:'fixed',inset:0,zIndex:195,overflow:'auto',background:'#07101f',color:'#fff',padding:24}}><div style={{maxWidth:1000,margin:'0 auto'}}><header style={{display:'flex',justifyContent:'space-between',alignItems:'flex-end',gap:12,marginBottom:16}}><div><div style={{color:'#73a7ff',fontSize:10,fontWeight:800,textTransform:'uppercase',letterSpacing:'.12em'}}>Privacy & Data</div><h1 style={{margin:'5px 0',fontSize:28}}>Privacidade & dados</h1><p style={{margin:0,color:'rgba(255,255,255,.5)',fontSize:11}}>Acesso, exportação e controlo dos dados que o Te-connect apresenta à sua conta.</p></div><div style={{display:'flex',gap:7}}><Button icon={RefreshCw} onClick={load}>Atualizar</Button><Button icon={X} onClick={onClose}>Fechar</Button></div></header>
 {message&&<div style={{marginBottom:12,padding:10,borderRadius:10,border:'1px solid rgba(239,103,123,.23)',background:'rgba(239,103,123,.07)',color:'#ff9aaa',fontSize:9}}>{message}</div>}
 <div style={{display:'grid',gridTemplateColumns:'1fr 1fr',gap:12}}><section style={card}><div style={head}><LockKeyhole size={16}/><strong style={{fontSize:13}}>Princípio de acesso</strong></div><p style={text}>Os módulos do Te-connect respeitam o tenant e as políticas de acesso do perfil. A área não altera permissões de base de dados; serve para consulta e exportação.</p><div style={note}><ShieldCheck size={14}/> Dados exportados diretamente da sessão autenticada.</div></section><section style={card}><div style={head}><UserRound size={16}/><strong style={{fontSize:13}}>{admin?'Exportação RH':'Exportação pessoal'}</strong></div><p style={text}>{admin?'Exporte uma cópia operacional da equipa para arquivo ou tratamento externo.':'Exporte uma cópia dos dados pessoais acessíveis à sua conta.'}</p><div style={{display:'flex',gap:7,marginTop:12}}><Button icon={FileJson} onClick={exportJson}>JSON</Button><Button primary icon={FileSpreadsheet} onClick={exportCsv}>{admin?'CSV da equipa':'CSV pessoal'}</Button></div></section></div>
 {loading?<div style={{minHeight:300,display:'grid',placeItems:'center',color:'rgba(255,255,255,.4)'}}>A preparar exportação…</div>:<section style={{...card,marginTop:12}}><div style={head}><Download size={16}/><strong style={{fontSize:13}}>Resumo do conjunto de dados</strong></div>{admin?<div style={{display:'grid',gridTemplateColumns:'repeat(4,1fr)',gap:8}}>{[['Colaboradores',data?.employees?.length||0],['Documentos',data?.documents?.length||0],['Formações',data?.training?.length||0],['Objetivos',data?.goals?.length||0]].map(([l,v])=><div key={l} style={{padding:11,borderRadius:10,background:'rgba(255,255,255,.03)',border:'1px solid rgba(255,255,255,.07)'}}><span style={{display:'block',fontSize:8,color:'rgba(255,255,255,.45)'}}>{l}</span><strong style={{display:'block',marginTop:4,fontSize:19}}>{v}</strong></div>)}</div>:<div style={{color:'rgba(255,255,255,.5)',fontSize:9}}>O pacote pessoal é limitado ao colaborador associado à sua sessão.</div>}</section>}
 </div></div>;
}
const card={border:'1px solid rgba(255,255,255,.09)',borderRadius:15,background:'rgba(255,255,255,.035)',padding:17};const head={display:'flex',alignItems:'center',gap:8};const text={color:'rgba(255,255,255,.5)',fontSize:9,lineHeight:1.6};const note={display:'flex',alignItems:'center',gap:6,marginTop:10,color:'rgba(255,255,255,.42)',fontSize:8};
