import { useCallback, useEffect, useState } from 'react';
import { KeyRound, LockKeyhole, QrCode, Shield, ShieldCheck, Smartphone, Trash2, X } from 'lucide-react';
import { createClient } from '@supabase/supabase-js';

const supabase = createClient(import.meta.env.VITE_SUPABASE_URL, import.meta.env.VITE_SUPABASE_PUBLISHABLE_KEY, { auth: { persistSession: true, autoRefreshToken: true } });

function Button({ children, icon: Icon, onClick, disabled, danger = false }) { return <button type="button" onClick={onClick} disabled={disabled} style={{ display:'inline-flex',alignItems:'center',justifyContent:'center',gap:7,padding:'9px 12px',borderRadius:9,border:danger?'1px solid rgba(239,100,120,.3)':'1px solid rgba(255,255,255,.1)',background:danger?'rgba(239,100,120,.08)':'rgba(255,255,255,.045)',color:'#fff',fontSize:9,opacity:disabled?.55:1 }}>{Icon&&<Icon size={14}/>} {children}</button>; }
function Field({ label, children }) { return <label style={{ display:'grid',gap:5,color:'rgba(255,255,255,.55)',fontSize:9 }}>{label}{children}</label>; }
const inputStyle={width:'100%',boxSizing:'border-box',padding:'10px',borderRadius:9,border:'1px solid rgba(255,255,255,.12)',background:'rgba(255,255,255,.045)',color:'#fff',fontSize:12,textAlign:'center',letterSpacing:'.2em'};

export default function SecurityCenter({ profile, onClose }) {
  const [aal, setAal] = useState(null); const [factors, setFactors] = useState([]); const [enroll, setEnroll] = useState(null); const [code, setCode] = useState(''); const [loading,setLoading]=useState(true); const [busy,setBusy]=useState(false); const [message,setMessage]=useState('');
  const load = useCallback(async()=>{setLoading(true);setMessage('');const [level,factorResult]=await Promise.all([supabase.auth.mfa.getAuthenticatorAssuranceLevel(),supabase.auth.mfa.listFactors()]);if(level.error)setMessage(level.error.message);else setAal(level.data);if(factorResult.error)setMessage(factorResult.error.message);else setFactors([...(factorResult.data?.totp||[]),...(factorResult.data?.phone||[])]);setLoading(false);},[]);
  useEffect(()=>{load();},[load]);
  const startEnroll=async()=>{setBusy(true);setMessage('');const {data,error}=await supabase.auth.mfa.enroll({factorType:'totp',friendlyName:`Te-connect · ${profile.full_name||'Conta'}`});if(error)setMessage(error.message);else setEnroll(data);setBusy(false);};
  const verifyEnroll=async()=>{if(!enroll?.id||!code.trim())return;setBusy(true);setMessage('');const challenge=await supabase.auth.mfa.challenge({factorId:enroll.id});if(challenge.error)setMessage(challenge.error.message);else{const result=await supabase.auth.mfa.verify({factorId:enroll.id,challengeId:challenge.data.id,code:code.trim()});if(result.error)setMessage(result.error.message);else{setMessage('MFA ativado nesta conta.');setEnroll(null);setCode('');await supabase.auth.refreshSession();await load();}}setBusy(false);};
  const removeFactor=async(id)=>{setBusy(true);setMessage('');const {error}=await supabase.auth.mfa.unenroll({factorId:id});if(error)setMessage(error.message);else{setMessage('Fator removido.');await load();}setBusy(false);};
  const qrSrc = enroll?.totp?.qr_code || '';
  return <div style={{position:'fixed',inset:0,zIndex:195,overflow:'auto',background:'#07101f',color:'#fff',padding:24}}><div style={{maxWidth:900,margin:'0 auto'}}>
    <header style={{display:'flex',justifyContent:'space-between',alignItems:'flex-end',gap:15,marginBottom:16}}><div><div style={{color:'#74a8ff',fontSize:10,fontWeight:800,textTransform:'uppercase',letterSpacing:'.12em'}}>Security & Account</div><h1 style={{margin:'5px 0',fontSize:28}}>Segurança da conta</h1><p style={{margin:0,color:'rgba(255,255,255,.5)',fontSize:11}}>Proteção da sessão, autenticação multifator e boas práticas de acesso.</p></div><div style={{display:'flex',gap:7}}><Button icon={Shield} onClick={load}>Atualizar</Button><Button icon={X} onClick={onClose}>Fechar</Button></div></header>
    {message&&<div style={{marginBottom:12,padding:10,borderRadius:10,border:'1px solid rgba(93,150,255,.25)',background:'rgba(55,112,255,.08)',color:'#b0c8ff',fontSize:9}}>{message}</div>}
    {loading?<div style={{minHeight:380,display:'grid',placeItems:'center',color:'rgba(255,255,255,.45)'}}>A verificar a sua segurança…</div>:<>
      <div style={{display:'grid',gridTemplateColumns:'1fr 1fr',gap:12,marginBottom:12}}>
        <section style={{border:'1px solid rgba(255,255,255,.09)',borderRadius:15,padding:17,background:'rgba(255,255,255,.035)'}}><div style={{display:'flex',alignItems:'center',gap:8}}><ShieldCheck size={17}/><strong style={{fontSize:12}}>Nível da sessão</strong></div><div style={{marginTop:14,padding:12,borderRadius:11,background:aal?.currentLevel==='aal2'?'rgba(39,201,132,.08)':'rgba(245,174,55,.08)',color:aal?.currentLevel==='aal2'?'#6bdfaa':'#e6bf6f'}}><strong style={{fontSize:19}}>{String(aal?.currentLevel||'aal1').toUpperCase()}</strong><span style={{display:'block',marginTop:4,fontSize:8,color:'rgba(255,255,255,.5)'}}>{aal?.currentLevel==='aal2'?'Sessão verificada com segundo fator.':'Sessão autenticada sem segundo fator.'}</span></div></section>
        <section style={{border:'1px solid rgba(255,255,255,.09)',borderRadius:15,padding:17,background:'rgba(255,255,255,.035)'}}><div style={{display:'flex',alignItems:'center',gap:8}}><LockKeyhole size={17}/><strong style={{fontSize:12}}>Proteção por password</strong></div><p style={{fontSize:9,color:'rgba(255,255,255,.5)',lineHeight:1.6}}>A proteção contra passwords comprometidas deve ser ativada nas definições Auth do projeto. Esta configuração é do Supabase e requer plano Pro ou superior.</p><div style={{padding:9,borderRadius:9,background:'rgba(245,174,55,.07)',color:'#e6bf6f',fontSize:8}}>Estado conhecido: proteção contra passwords vazadas ainda pendente de ativação.</div></section>
      </div>
      <section style={{border:'1px solid rgba(255,255,255,.09)',borderRadius:15,padding:17,background:'rgba(255,255,255,.035)',marginBottom:12}}><div style={{display:'flex',justifyContent:'space-between',alignItems:'center',gap:10}}><div><div style={{display:'flex',alignItems:'center',gap:8}}><Smartphone size={17}/><strong style={{fontSize:13}}>Autenticação multifator (TOTP)</strong></div><p style={{margin:'5px 0 0',color:'rgba(255,255,255,.5)',fontSize:9}}>Use um aplicativo autenticador compatível para proteger contas com acesso ao RH.</p></div>{!factors.length&&!enroll&&<Button icon={QrCode} onClick={startEnroll} disabled={busy}>Ativar MFA</Button>}</div>
        {!!factors.length&&<div style={{display:'grid',gap:7,marginTop:14}}>{factors.map((factor)=><div key={factor.id} style={{display:'flex',justifyContent:'space-between',alignItems:'center',gap:12,padding:11,borderRadius:10,background:'rgba(39,201,132,.05)',border:'1px solid rgba(39,201,132,.12)'}}><div><strong style={{display:'block',fontSize:10}}>{factor.friendly_name||'Authenticator'}</strong><small style={{display:'block',marginTop:3,color:'rgba(255,255,255,.45)',fontSize:8}}>{factor.factor_type||factor.type||'TOTP'} · {factor.status||'verified'}</small></div><Button icon={Trash2} danger disabled={busy} onClick={()=>removeFactor(factor.id)}>Remover</Button></div>)}</div>}
        {!factors.length&&!enroll&&<div style={{marginTop:14,padding:11,border:'1px dashed rgba(255,255,255,.12)',color:'rgba(255,255,255,.45)',fontSize:9}}>Nenhum fator MFA verificado nesta conta.</div>}
        {enroll&&<div style={{marginTop:15,display:'grid',gridTemplateColumns:'220px 1fr',gap:18,alignItems:'center'}}><div style={{padding:13,borderRadius:12,background:'#fff',display:'grid',placeItems:'center'}}>{qrSrc?<img src={qrSrc} alt="QR Code MFA" style={{width:190,height:190}}/>:<div style={{width:190,height:190,display:'grid',placeItems:'center',color:'#111',fontSize:10}}>QR Code indisponível</div>}</div><div><h3 style={{margin:'0 0 7px',fontSize:14}}>1. Digitalize o QR Code</h3><p style={{fontSize:9,color:'rgba(255,255,255,.5)',lineHeight:1.55}}>Abra a aplicação autenticadora e adicione a conta através deste QR Code. Depois introduza o código de 6 dígitos abaixo.</p><div style={{margin:'10px 0',padding:9,borderRadius:9,background:'rgba(255,255,255,.035)',fontSize:8,color:'rgba(255,255,255,.5)',wordBreak:'break-all'}}>Chave manual: {enroll.totp.secret}</div><Field label="Código de verificação"><input value={code} onChange={(e)=>setCode(e.target.value.replace(/\D/g,'').slice(0,6))} inputMode="numeric" maxLength={6} placeholder="000000" style={inputStyle}/></Field><div style={{display:'flex',gap:7,marginTop:10}}><Button onClick={()=>{setEnroll(null);setCode('');}} disabled={busy}>Cancelar</Button><Button onClick={verifyEnroll} disabled={busy||code.length!==6} icon={KeyRound}>Verificar e ativar</Button></div></div></div>}
      </section>
      <section style={{border:'1px solid rgba(255,255,255,.09)',borderRadius:15,padding:17,background:'rgba(255,255,255,.035)'}}><div style={{display:'flex',alignItems:'center',gap:8}}><KeyRound size={17}/><strong style={{fontSize:13}}>Práticas de segurança</strong></div><div style={{display:'grid',gap:8,marginTop:12}}>{['Nunca partilhe passwords ou códigos MFA.','Use uma password única e forte para a conta.','Ative MFA em contas de administração e RH.','Remova fatores MFA antigos quando trocar de dispositivo.'].map((item)=><div key={item} style={{display:'flex',gap:8,fontSize:9,color:'rgba(255,255,255,.55)'}}><ShieldCheck size={14} style={{color:'#5edca4',flex:'0 0 auto'}}/>{item}</div>)}</div></section>
    </>}</div></div>;
}
