-- Normalize permissive SELECT/ALL pairs into action-specific policies.
-- Preserves tenant and role boundaries while avoiding overlapping SELECT evaluation.

drop policy if exists absence_types_manage on public.absence_types;
create policy absence_types_insert on public.absence_types for insert to authenticated with check ((company_id = private.current_profile_company_id()) and (private.current_profile_role() = any (array['SUPER_ADMIN','COMPANY_ADMIN','RH'])));
create policy absence_types_update on public.absence_types for update to authenticated using ((company_id = private.current_profile_company_id()) and (private.current_profile_role() = any (array['SUPER_ADMIN','COMPANY_ADMIN','RH']))) with check ((company_id = private.current_profile_company_id()) and (private.current_profile_role() = any (array['SUPER_ADMIN','COMPANY_ADMIN','RH'])));
create policy absence_types_delete on public.absence_types for delete to authenticated using ((company_id = private.current_profile_company_id()) and (private.current_profile_role() = any (array['SUPER_ADMIN','COMPANY_ADMIN','RH'])));

drop policy if exists absences_manage on public.absences;
create policy absences_insert on public.absences for insert to authenticated with check ((company_id = private.current_profile_company_id()) and (private.is_company_admin_or_hr() or (private.is_manager() and private.is_managed_employee(employee_id))) and exists (select 1 from employees e where e.id = absences.employee_id and e.company_id = private.current_profile_company_id()));
create policy absences_update on public.absences for update to authenticated using ((company_id = private.current_profile_company_id()) and (private.is_company_admin_or_hr() or (private.is_manager() and private.is_managed_employee(employee_id))) and exists (select 1 from employees e where e.id = absences.employee_id and e.company_id = private.current_profile_company_id())) with check ((company_id = private.current_profile_company_id()) and (private.is_company_admin_or_hr() or (private.is_manager() and private.is_managed_employee(employee_id))) and exists (select 1 from employees e where e.id = absences.employee_id and e.company_id = private.current_profile_company_id()));
create policy absences_delete on public.absences for delete to authenticated using ((company_id = private.current_profile_company_id()) and (private.is_company_admin_or_hr() or (private.is_manager() and private.is_managed_employee(employee_id))) and exists (select 1 from employees e where e.id = absences.employee_id and e.company_id = private.current_profile_company_id()));

drop policy if exists company_settings_manage on public.company_settings;
create policy company_settings_insert on public.company_settings for insert to authenticated with check ((company_id = private.current_profile_company_id()) and (private.current_profile_role() = any (array['SUPER_ADMIN','COMPANY_ADMIN','RH'])));
create policy company_settings_update on public.company_settings for update to authenticated using ((company_id = private.current_profile_company_id()) and (private.current_profile_role() = any (array['SUPER_ADMIN','COMPANY_ADMIN','RH']))) with check ((company_id = private.current_profile_company_id()) and (private.current_profile_role() = any (array['SUPER_ADMIN','COMPANY_ADMIN','RH'])));
create policy company_settings_delete on public.company_settings for delete to authenticated using ((company_id = private.current_profile_company_id()) and (private.current_profile_role() = any (array['SUPER_ADMIN','COMPANY_ADMIN','RH'])));

drop policy if exists employee_competencies_manage on public.employee_competencies;
create policy employee_competencies_insert on public.employee_competencies for insert to authenticated with check ((company_id = private.current_profile_company_id()) and (private.is_company_admin_or_hr() or (private.is_manager() and private.is_managed_employee(employee_id))) and exists (select 1 from employees e where e.id = employee_competencies.employee_id and e.company_id = private.current_profile_company_id()));
create policy employee_competencies_update on public.employee_competencies for update to authenticated using ((company_id = private.current_profile_company_id()) and (private.is_company_admin_or_hr() or (private.is_manager() and private.is_managed_employee(employee_id))) and exists (select 1 from employees e where e.id = employee_competencies.employee_id and e.company_id = private.current_profile_company_id())) with check ((company_id = private.current_profile_company_id()) and (private.is_company_admin_or_hr() or (private.is_manager() and private.is_managed_employee(employee_id))) and exists (select 1 from employees e where e.id = employee_competencies.employee_id and e.company_id = private.current_profile_company_id()));
create policy employee_competencies_delete on public.employee_competencies for delete to authenticated using ((company_id = private.current_profile_company_id()) and (private.is_company_admin_or_hr() or (private.is_manager() and private.is_managed_employee(employee_id))) and exists (select 1 from employees e where e.id = employee_competencies.employee_id and e.company_id = private.current_profile_company_id()));

drop policy if exists employee_documents_manage on public.employee_documents;
create policy employee_documents_insert on public.employee_documents for insert to authenticated with check ((company_id = private.current_profile_company_id()) and (private.is_company_admin_or_hr() or (private.is_manager() and private.is_managed_employee(employee_id))) and exists (select 1 from employees e where e.id = employee_documents.employee_id and e.company_id = private.current_profile_company_id()));
create policy employee_documents_update on public.employee_documents for update to authenticated using ((company_id = private.current_profile_company_id()) and (private.is_company_admin_or_hr() or (private.is_manager() and private.is_managed_employee(employee_id))) and exists (select 1 from employees e where e.id = employee_documents.employee_id and e.company_id = private.current_profile_company_id())) with check ((company_id = private.current_profile_company_id()) and (private.is_company_admin_or_hr() or (private.is_manager() and private.is_managed_employee(employee_id))) and exists (select 1 from employees e where e.id = employee_documents.employee_id and e.company_id = private.current_profile_company_id()));
create policy employee_documents_delete on public.employee_documents for delete to authenticated using ((company_id = private.current_profile_company_id()) and (private.is_company_admin_or_hr() or (private.is_manager() and private.is_managed_employee(employee_id))) and exists (select 1 from employees e where e.id = employee_documents.employee_id and e.company_id = private.current_profile_company_id()));

drop policy if exists employee_trainings_manage on public.employee_trainings;
create policy employee_trainings_insert on public.employee_trainings for insert to authenticated with check ((company_id = private.current_profile_company_id()) and (private.is_company_admin_or_hr() or (private.is_manager() and private.is_managed_employee(employee_id))) and exists (select 1 from employees e where e.id = employee_trainings.employee_id and e.company_id = private.current_profile_company_id()));
create policy employee_trainings_update on public.employee_trainings for update to authenticated using ((company_id = private.current_profile_company_id()) and (private.is_company_admin_or_hr() or (private.is_manager() and private.is_managed_employee(employee_id))) and exists (select 1 from employees e where e.id = employee_trainings.employee_id and e.company_id = private.current_profile_company_id())) with check ((company_id = private.current_profile_company_id()) and (private.is_company_admin_or_hr() or (private.is_manager() and private.is_managed_employee(employee_id))) and exists (select 1 from employees e where e.id = employee_trainings.employee_id and e.company_id = private.current_profile_company_id()));
create policy employee_trainings_delete on public.employee_trainings for delete to authenticated using ((company_id = private.current_profile_company_id()) and (private.is_company_admin_or_hr() or (private.is_manager() and private.is_managed_employee(employee_id))) and exists (select 1 from employees e where e.id = employee_trainings.employee_id and e.company_id = private.current_profile_company_id()));

drop policy if exists holidays_manage on public.holidays;
create policy holidays_insert on public.holidays for insert to authenticated with check ((company_id = private.current_profile_company_id()) and (private.current_profile_role() = any (array['SUPER_ADMIN','COMPANY_ADMIN','RH'])));
create policy holidays_update on public.holidays for update to authenticated using ((company_id = private.current_profile_company_id()) and (private.current_profile_role() = any (array['SUPER_ADMIN','COMPANY_ADMIN','RH']))) with check ((company_id = private.current_profile_company_id()) and (private.current_profile_role() = any (array['SUPER_ADMIN','COMPANY_ADMIN','RH'])));
create policy holidays_delete on public.holidays for delete to authenticated using ((company_id = private.current_profile_company_id()) and (private.current_profile_role() = any (array['SUPER_ADMIN','COMPANY_ADMIN','RH'])));

drop policy if exists overtime_manage_role_scoped on public.overtime_records;
create policy overtime_insert on public.overtime_records for insert to authenticated with check ((company_id = private.current_profile_company_id()) and (private.is_company_admin_or_hr() or (private.is_manager() and private.is_managed_employee(employee_id))) and exists (select 1 from employees e where e.id = overtime_records.employee_id and e.company_id = private.current_profile_company_id()));
create policy overtime_update on public.overtime_records for update to authenticated using ((company_id = private.current_profile_company_id()) and (private.is_company_admin_or_hr() or (private.is_manager() and private.is_managed_employee(employee_id))) and exists (select 1 from employees e where e.id = overtime_records.employee_id and e.company_id = private.current_profile_company_id())) with check ((company_id = private.current_profile_company_id()) and (private.is_company_admin_or_hr() or (private.is_manager() and private.is_managed_employee(employee_id))) and exists (select 1 from employees e where e.id = overtime_records.employee_id and e.company_id = private.current_profile_company_id()));
create policy overtime_delete on public.overtime_records for delete to authenticated using ((company_id = private.current_profile_company_id()) and (private.is_company_admin_or_hr() or (private.is_manager() and private.is_managed_employee(employee_id))) and exists (select 1 from employees e where e.id = overtime_records.employee_id and e.company_id = private.current_profile_company_id()));

drop policy if exists performance_cycles_manage on public.performance_cycles;
create policy performance_cycles_insert on public.performance_cycles for insert to authenticated with check ((company_id = private.current_profile_company_id()) and private.is_company_admin_or_hr());
create policy performance_cycles_update on public.performance_cycles for update to authenticated using ((company_id = private.current_profile_company_id()) and private.is_company_admin_or_hr()) with check ((company_id = private.current_profile_company_id()) and private.is_company_admin_or_hr());
create policy performance_cycles_delete on public.performance_cycles for delete to authenticated using ((company_id = private.current_profile_company_id()) and private.is_company_admin_or_hr());

drop policy if exists recruitment_candidates_manage on public.recruitment_candidates;
drop policy if exists recruitment_candidates_select on public.recruitment_candidates;
create policy recruitment_candidates_select on public.recruitment_candidates for select to authenticated using ((company_id = private.current_profile_company_id()) and private.is_company_admin_or_hr());
create policy recruitment_candidates_insert on public.recruitment_candidates for insert to authenticated with check ((company_id = private.current_profile_company_id()) and private.is_company_admin_or_hr());
create policy recruitment_candidates_update on public.recruitment_candidates for update to authenticated using ((company_id = private.current_profile_company_id()) and private.is_company_admin_or_hr()) with check ((company_id = private.current_profile_company_id()) and private.is_company_admin_or_hr());
create policy recruitment_candidates_delete on public.recruitment_candidates for delete to authenticated using ((company_id = private.current_profile_company_id()) and private.is_company_admin_or_hr());

drop policy if exists recruitment_interviews_manage on public.recruitment_interviews;
drop policy if exists recruitment_interviews_select on public.recruitment_interviews;
create policy recruitment_interviews_select on public.recruitment_interviews for select to authenticated using ((company_id = private.current_profile_company_id()) and private.is_company_admin_or_hr());
create policy recruitment_interviews_insert on public.recruitment_interviews for insert to authenticated with check ((company_id = private.current_profile_company_id()) and private.is_company_admin_or_hr());
create policy recruitment_interviews_update on public.recruitment_interviews for update to authenticated using ((company_id = private.current_profile_company_id()) and private.is_company_admin_or_hr()) with check ((company_id = private.current_profile_company_id()) and private.is_company_admin_or_hr());
create policy recruitment_interviews_delete on public.recruitment_interviews for delete to authenticated using ((company_id = private.current_profile_company_id()) and private.is_company_admin_or_hr());

drop policy if exists recruitment_jobs_manage on public.recruitment_jobs;
drop policy if exists recruitment_jobs_select on public.recruitment_jobs;
create policy recruitment_jobs_select on public.recruitment_jobs for select to authenticated using ((company_id = private.current_profile_company_id()) and private.is_company_admin_or_hr());
create policy recruitment_jobs_insert on public.recruitment_jobs for insert to authenticated with check ((company_id = private.current_profile_company_id()) and private.is_company_admin_or_hr());
create policy recruitment_jobs_update on public.recruitment_jobs for update to authenticated using ((company_id = private.current_profile_company_id()) and private.is_company_admin_or_hr()) with check ((company_id = private.current_profile_company_id()) and private.is_company_admin_or_hr());
create policy recruitment_jobs_delete on public.recruitment_jobs for delete to authenticated using ((company_id = private.current_profile_company_id()) and private.is_company_admin_or_hr());

drop policy if exists adjustments_manage_role_scoped on public.timesheet_adjustments;
create policy adjustments_insert on public.timesheet_adjustments for insert to authenticated with check ((company_id = private.current_profile_company_id()) and (private.is_company_admin_or_hr() or (private.is_manager() and private.is_managed_employee(employee_id))) and exists (select 1 from employees e where e.id = timesheet_adjustments.employee_id and e.company_id = private.current_profile_company_id()));
create policy adjustments_update on public.timesheet_adjustments for update to authenticated using ((company_id = private.current_profile_company_id()) and (private.is_company_admin_or_hr() or (private.is_manager() and private.is_managed_employee(employee_id))) and exists (select 1 from employees e where e.id = timesheet_adjustments.employee_id and e.company_id = private.current_profile_company_id())) with check ((company_id = private.current_profile_company_id()) and (private.is_company_admin_or_hr() or (private.is_manager() and private.is_managed_employee(employee_id))) and exists (select 1 from employees e where e.id = timesheet_adjustments.employee_id and e.company_id = private.current_profile_company_id()));
create policy adjustments_delete on public.timesheet_adjustments for delete to authenticated using ((company_id = private.current_profile_company_id()) and (private.is_company_admin_or_hr() or (private.is_manager() and private.is_managed_employee(employee_id))) and exists (select 1 from employees e where e.id = timesheet_adjustments.employee_id and e.company_id = private.current_profile_company_id()));

drop policy if exists training_courses_manage on public.training_courses;
create policy training_courses_insert on public.training_courses for insert to authenticated with check ((company_id = private.current_profile_company_id()) and private.is_company_admin_or_hr());
create policy training_courses_update on public.training_courses for update to authenticated using ((company_id = private.current_profile_company_id()) and private.is_company_admin_or_hr()) with check ((company_id = private.current_profile_company_id()) and private.is_company_admin_or_hr());
create policy training_courses_delete on public.training_courses for delete to authenticated using ((company_id = private.current_profile_company_id()) and private.is_company_admin_or_hr());

drop policy if exists vacation_balances_manage_hr on public.vacation_balances;
create policy vacation_balances_insert on public.vacation_balances for insert to authenticated with check ((company_id = private.current_profile_company_id()) and private.is_company_admin_or_hr());
create policy vacation_balances_update on public.vacation_balances for update to authenticated using ((company_id = private.current_profile_company_id()) and private.is_company_admin_or_hr()) with check ((company_id = private.current_profile_company_id()) and private.is_company_admin_or_hr());
create policy vacation_balances_delete on public.vacation_balances for delete to authenticated using ((company_id = private.current_profile_company_id()) and private.is_company_admin_or_hr());

drop policy if exists vacation_requests_manage on public.vacation_requests;
create policy vacation_requests_insert on public.vacation_requests for insert to authenticated with check ((company_id = private.current_profile_company_id()) and (private.is_company_admin_or_hr() or (private.is_manager() and private.is_managed_employee(employee_id))) and exists (select 1 from employees e where e.id = vacation_requests.employee_id and e.company_id = private.current_profile_company_id()));
create policy vacation_requests_update on public.vacation_requests for update to authenticated using ((company_id = private.current_profile_company_id()) and (private.is_company_admin_or_hr() or (private.is_manager() and private.is_managed_employee(employee_id))) and exists (select 1 from employees e where e.id = vacation_requests.employee_id and e.company_id = private.current_profile_company_id())) with check ((company_id = private.current_profile_company_id()) and (private.is_company_admin_or_hr() or (private.is_manager() and private.is_managed_employee(employee_id))) and exists (select 1 from employees e where e.id = vacation_requests.employee_id and e.company_id = private.current_profile_company_id()));
create policy vacation_requests_delete on public.vacation_requests for delete to authenticated using ((company_id = private.current_profile_company_id()) and (private.is_company_admin_or_hr() or (private.is_manager() and private.is_managed_employee(employee_id))) and exists (select 1 from employees e where e.id = vacation_requests.employee_id and e.company_id = private.current_profile_company_id()));
