import "jsr:@supabase/functions-js/edge-runtime.d.ts";
import { createClient } from "https://esm.sh/@supabase/supabase-js@2.57.4";

const supabaseUrl = Deno.env.get("SUPABASE_URL")!;
const serviceKey = Deno.env.get("SUPABASE_SERVICE_ROLE_KEY")!;
const admin = createClient(supabaseUrl, serviceKey, { auth: { persistSession: false } });
const cors = { "Access-Control-Allow-Origin":"*", "Access-Control-Allow-Headers":"content-type,x-teconnect-api-key", "Access-Control-Allow-Methods":"GET,OPTIONS" };
const json=(body:unknown,status=200)=>new Response(JSON.stringify(body),{status,headers:{...cors,"Content-Type":"application/json; charset=utf-8","Cache-Control":"no-store"}});
async function sha256Hex(value:string){const bytes=new TextEncoder().encode(value);const hash=await crypto.subtle.digest("SHA-256",bytes);return Array.from(new Uint8Array(hash)).map((b)=>b.toString(16).padStart(2,"0")).join("")}
async function authenticate(req:Request){const raw=req.headers.get("x-teconnect-api-key")?.trim()||"";if(!raw.startsWith("tc_live_")||raw.length<20)return null;const {data,error}=await admin.rpc("resolve_api_key_internal",{p_secret_hash:await sha256Hex(raw)});if(error||!data?.id||!data.active)return null;if(data.expires_at&&new Date(data.expires_at)<=new Date())return null;await admin.from("app_api_keys").update({last_used_at:new Date().toISOString()}).eq("id",data.id);return data}
Deno.serve(async(req)=>{if(req.method==="OPTIONS")return new Response("ok",{headers:cors});if(req.method!=="GET")return json({error:"METHOD_NOT_ALLOWED"},405);const apiKey=await authenticate(req);if(!apiKey)return json({error:"INVALID_API_KEY"},401);const url=new URL(req.url);const route=url.pathname.replace(/\/+$/,'')||'/';const companyId=apiKey.company_id as string;if(route==='/v1/health')return json({ok:true,service:'teconnect-api',company_id:companyId,timestamp:new Date().toISOString()});if(route==='/v1/employees'){const limit=Math.min(Math.max(Number(url.searchParams.get('limit')||100),1),500);const offset=Math.max(Number(url.searchParams.get('offset')||0),0);const {data,error}=await admin.from('employees').select('id,employee_code,full_name,email,phone,department_id,position_id,hire_date,status,manager_id,created_at').eq('company_id',companyId).order('full_name').range(offset,offset+limit-1);if(error)return json({error:'DATABASE_ERROR'},500);return json({data:data||[],pagination:{limit,offset,count:data?.length||0}})}if(route==='/v1/attendance'){const from=url.searchParams.get('from');const to=url.searchParams.get('to');const limit=Math.min(Math.max(Number(url.searchParams.get('limit')||100),1),500);let query=admin.from('attendance_days').select('id,employee_id,work_date,scheduled_minutes,worked_minutes,normal_minutes,overtime_minutes,late_minutes,early_leave_minutes,night_minutes,status,first_clock_in,last_clock_out').eq('company_id',companyId).order('work_date',{ascending:false}).limit(limit);if(from)query=query.gte('work_date',from);if(to)query=query.lte('work_date',to);const {data,error}=await query;if(error)return json({error:'DATABASE_ERROR'},500);return json({data:data||[],filter:{from:from||null,to:to||null},count:data?.length||0})}return json({error:'NOT_FOUND',routes:['/v1/health','/v1/employees','/v1/attendance']},404)});
